import { spawnSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import type { AdapterTesterConfig } from "./config.js";
import { startDevServer } from "./devServer.js";
import { resolveConfig } from "./fileConfig.js";
import type { HarnessWebServerConfig } from "./harness/mantineSourceOfTruth.js";

// `dist/testing.js` is always a sibling of this file — both inside a
// consumer's node_modules/@recursica/adapter-tester/dist and inside this
// monorepo's own packages/adapter-tester/dist when self-hosting — so the
// generated spec below can reach it without depending on how the package
// itself resolves at import time.
const distDir = dirname(fileURLToPath(import.meta.url));
const testingEntry = pathToFileURL(join(distDir, "testing.js")).href;

const cwd = process.cwd();
const { engineConfig, webServers } = resolveConfig(cwd);

if (process.argv.includes("--dry-run")) {
  console.log(JSON.stringify({ engineConfig, webServers }, null, 2));
  process.exit(0);
}

// Any arg besides our own `--dry-run`/`--serve` flags is passed straight
// through to `playwright test` — e.g. `npm run adapter-tester:automated --
// --grep "Toast"` to scope a run to matching stories, instead of every
// invocation running the full suite.
const OWN_FLAGS = new Set(["--dry-run", "--serve"]);
const passthroughArgs = process.argv
  .slice(2)
  .filter((arg) => !OWN_FLAGS.has(arg));

if (process.argv.includes("--serve")) {
  // Dual-Storybook interactive Dev Mode — no Playwright, no screenshots.
  // Used by the `adapter-tester` npm script.
  startDevServer(engineConfig, webServers);
} else {
  runAutomated(webServers, engineConfig);
}

/**
 * Generates a throwaway Playwright config + spec under `.adapter-tester/run/`
 * and runs the automated pixel-diff suite. Used by the
 * `adapter-tester:automated` npm script.
 */
function runAutomated(
  servers: HarnessWebServerConfig[],
  config: AdapterTesterConfig,
): void {
  const runDir = join(cwd, ".adapter-tester/run");
  mkdirSync(runDir, { recursive: true });

  writeFileSync(
    join(runDir, "playwright.config.js"),
    `// Generated by \`adapter-tester\` — do not edit, regenerated on every run.
import { defineConfig, devices } from "@playwright/test";

export default defineConfig({
  testDir: ${JSON.stringify(runDir)},
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: [["html", { open: "never" }], ["list"]],
  use: { trace: "on-first-retry" },
  projects: [{ name: "chromium", use: { ...devices["Desktop Chrome"] } }],
  webServer: ${JSON.stringify(servers, null, 2)},
});
`,
  );

  writeFileSync(
    join(runDir, "visual-regression.spec.js"),
    `// Generated by \`adapter-tester\` — do not edit, regenerated on every run.
import { runVisualRegression } from ${JSON.stringify(testingEntry)};

await runVisualRegression(${JSON.stringify(config, null, 2)});
`,
  );

  const result = spawnSync(
    "npx",
    [
      "playwright",
      "test",
      "--config",
      join(runDir, "playwright.config.js"),
      ...passthroughArgs,
    ],
    { stdio: "inherit", cwd, shell: process.platform === "win32" },
  );

  process.exit(result.status ?? 1);
}
