import { spawnSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import type { AdapterTesterConfig } from "./config.js";
import { startDevServer } from "./devServer.js";
import { resolveConfig } from "./fileConfig.js";
import type { HarnessWebServerConfig } from "./harness/mantineSourceOfTruth.js";

// `dist/testing.js` is always a sibling of this file — both inside a
// consumer's node_modules/@recursica/adapter-tester/dist and inside this
// monorepo's own packages/adapter-tester/dist when self-hosting — so the
// generated spec below can reach it without depending on how the package
// itself resolves at import time.
const distDir = dirname(fileURLToPath(import.meta.url));
const testingEntry = pathToFileURL(join(distDir, "testing.js")).href;

// `--source-of-truth-version <value>` takes a value, unlike every other own
// flag below — pulled out of argv first so the boolean flags/passthrough
// logic never has to know it exists.
const args = process.argv.slice(2);
let sourceOfTruthVersion: string | undefined;
const sourceOfTruthVersionFlagIndex = args.indexOf("--source-of-truth-version");
if (sourceOfTruthVersionFlagIndex !== -1) {
  const value = args[sourceOfTruthVersionFlagIndex + 1];
  if (value === undefined || value.startsWith("--")) {
    throw new Error(
      "--source-of-truth-version requires a value, e.g. --source-of-truth-version 0.53.0",
    );
  }
  sourceOfTruthVersion = value;
  args.splice(sourceOfTruthVersionFlagIndex, 2);
}

const cwd = process.cwd();
const { engineConfig, webServers } = resolveConfig(cwd, {
  mantineAdapterVersion: sourceOfTruthVersion,
});

if (args.includes("--update-golden")) {
  engineConfig.goldenMode = "update-golden";
} else if (args.includes("--approve-divergence")) {
  engineConfig.goldenMode = "approve-divergence";
}

if (args.includes("--divergence-only")) {
  if (engineConfig.isSourceOfTruthAdapter) {
    throw new Error(
      "--divergence-only has nothing to diverge from — isSourceOfTruthAdapter is true in this project's adapter-tester.config.json.",
    );
  }
  engineConfig.checkMode = "divergence";
} else if (engineConfig.goldenMode === "approve-divergence") {
  throw new Error(
    "--approve-divergence only makes sense with --divergence-only — there's nothing to approve without the divergence check running.",
  );
}

if (args.includes("--dry-run")) {
  console.log(JSON.stringify({ engineConfig, webServers }, null, 2));
  process.exit(0);
}

// Any arg besides our own flags is passed straight through to `playwright
// test` — e.g. `npm run adapter-tester:automated -- --grep "Toast"` to scope
// a run to matching stories, instead of every invocation running the full
// suite. Our own flags are consumed above, not forwarded — Playwright itself
// doesn't know about them.
const OWN_FLAGS = new Set([
  "--dry-run",
  "--serve",
  "--update-golden",
  "--approve-divergence",
  "--divergence-only",
]);
const passthroughArgs = args.filter((arg) => !OWN_FLAGS.has(arg));

if (args.includes("--serve")) {
  if (engineConfig.isSourceOfTruthAdapter) {
    throw new Error(
      "Dev Mode (--serve) has nothing to sync this project's Storybook against — isSourceOfTruthAdapter is true in this project's adapter-tester.config.json.",
    );
  }
  // Dual-Storybook interactive Dev Mode — no Playwright, no screenshots.
  // Used by the `adapter-tester` npm script.
  startDevServer(engineConfig, webServers);
} else {
  // The golden-image checks never need the source-of-truth adapter's own
  // Storybook running — the divergence check reads its stored golden files,
  // not a live page — so only the last (own) webServer is booted here. Dev
  // Mode above is the one thing that still needs both.
  runAutomated(webServers.slice(-1), engineConfig);
}

/**
 * Generates a throwaway Playwright config + spec under `.adapter-tester/run/`
 * and runs the automated pixel-diff suite. Used by the
 * `adapter-tester:automated` npm script.
 */
function runAutomated(
  servers: HarnessWebServerConfig[],
  config: AdapterTesterConfig,
): void {
  const runDir = join(cwd, ".adapter-tester/run");
  mkdirSync(runDir, { recursive: true });

  writeFileSync(
    join(runDir, "playwright.config.js"),
    `// Generated by \`adapter-tester\` — do not edit, regenerated on every run.
import { defineConfig, devices } from "@playwright/test";

export default defineConfig({
  testDir: ${JSON.stringify(runDir)},
  // Stories run across Playwright's default worker pool — each golden check
  // only reads/writes its own story's manifest.json entry, under a lock, so
  // concurrent workers never race each other (see \`updateManifestEntry\`).
  // Override with \`--workers <n>\` (forwarded straight through to Playwright).
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  reporter: [["html", { open: "never" }], ["list"]],
  use: { trace: "on-first-retry" },
  projects: [{ name: "chromium", use: { ...devices["Desktop Chrome"] } }],
  webServer: ${JSON.stringify(servers, null, 2)},
});
`,
  );

  writeFileSync(
    join(runDir, "visual-regression.spec.js"),
    `// Generated by \`adapter-tester\` — do not edit, regenerated on every run.
import { test } from "@playwright/test";
import { resolveVisualRegressionPlan } from ${JSON.stringify(testingEntry)};

// \`test.describe\`/\`test\` are called here, not inside resolveVisualRegressionPlan,
// so Playwright's HTML report groups the suite under this file instead of a
// sourcemapped path into adapter-tester's own library code.
const { ownTargetName, suiteLabel, stories, checkStory } =
  await resolveVisualRegressionPlan(${JSON.stringify(config, null, 2)});

test.describe(\`\${ownTargetName} — \${suiteLabel}\`, () => {
  for (const story of stories) {
    test(story.id, async ({ browser }, testInfo) => {
      await checkStory(story, browser, testInfo);
    });
  }
});
`,
  );

  const result = spawnSync(
    "npx",
    [
      "playwright",
      "test",
      "--config",
      join(runDir, "playwright.config.js"),
      ...passthroughArgs,
    ],
    { stdio: "inherit", cwd, shell: process.platform === "win32" },
  );

  process.exit(result.status ?? 1);
}
