/* prettier-ignore */
/* eslint-disable */
/* tslint:disable */
/*
Auto-generated by Recursica.
Do NOT edit these files directly

For more information about Recursica, go to https://recursica.com
*/

export type RecursicaSpacersType = 
	"size/spacer/2x" |
	"size/spacer/1-5x" |
	"size/spacer/default" |
	"size/spacer/4x" |
	"size/spacer/0-5x" |
	"size/spacer/3x";
