/* prettier-ignore */
/* eslint-disable */
/* tslint:disable */
/*
Auto-generated by Recursica.
Do NOT edit these files directly

For more information about Recursica, go to https://recursica.com
*/
export { RecursicaBrandLightTheme } from './RecursicaRecursicaRecursicaBrandLightTheme.css';
import { RecursicaBrandLightTheme } from './RecursicaRecursicaRecursicaBrandLightTheme.css';
export { RecursicaBrandDarkTheme } from './RecursicaRecursicaRecursicaBrandDarkTheme.css';
import { RecursicaBrandDarkTheme } from './RecursicaRecursicaRecursicaBrandDarkTheme.css';

export const Themes = {
  'RecursicaBrand': {
    'Light': RecursicaBrandLightTheme,
		'Dark': RecursicaBrandDarkTheme
  }
}