/* prettier-ignore */
/* eslint-disable */
/* tslint:disable */
/*
Auto-generated by Recursica.
Do NOT edit these files directly

For more information about Recursica, go to https://recursica.com
*/

import { colorsTuple, createTheme } from '@mantine/core'
import { themeVars } from './RecursicaRecursicaContractTheme.css'
import { recursica } from './Recursica'

export const mantineTheme = createTheme({
  primaryColor: 'color-1-scale-default',
  
  breakpoints: {
    
  },
  components: {
    "accordion": { 
			styles:{ 
				root: { 
					"lavel": recursica['color-on/background/high-emphasis'],
					"chevron": recursica['color-on/background/high-emphasis'],
					"stroke": recursica['color/stroke/default'],
					"padding": recursica['size/spacer/2x'],
					"spacing": recursica['size/spacer/2x'],
					"min-width": "140px",
					"max-width": "464px",
					"height": "56px",
					"cheveron": "24px" 
				} 
			} 
		},
		"action-bar": { 
			styles:{ 
				root: { 
					"background": recursica['color/surface/default'],
					"vertical-padding": recursica['size/spacer/2x'],
					"horizontal-padding": recursica['size/spacer/default'],
					"spacing": recursica['size/spacer/default'] 
				} 
			} 
		},
		"avatar": { 
			styles:{ 
				root: { 
					"background-contained": recursica['color/1-scale/default'],
					"background-outline": recursica['color/surface/default'],
					"stroke-contained": recursica['color-on/1-scale/default/high-emphasis'],
					"stroke-outline": recursica['color/1-scale/default'],
					"label-contained": recursica['color-on/1-scale/default/high-emphasis'],
					"label-outline": recursica['color/1-scale/default'],
					"small": "24px",
					"default": "32px",
					"large": "40px",
					"icon-size": "20px" 
				} 
			} 
		},
		"badge": { 
			styles:{ 
				root: { 
					"background-default": recursica['color/surface/default'],
					"background-primary": recursica['color/1-scale/default'],
					"background-alert": recursica['color/alert/default'],
					"background-success": recursica['color/success/default'],
					"label-default": recursica['color-on/surface/high-emphasis'],
					"label-primary": recursica['color-on/1-scale/default/high-emphasis'],
					"label-alert": recursica['color-on/alert/default/high-emphasis'],
					"label-success": recursica['color-on/success/default/high-emphasis'],
					"counter-horizontal-padding": recursica['size/spacer/0-5x'],
					"message-horizontal-padding": recursica['size/spacer/default'],
					"large-vertical-padding": recursica['size/spacer/0-5x'],
					"default-min-width": "16px",
					"default-height": "16px",
					"large-min-width": "24px",
					"large-height": "24px" 
				} 
			} 
		},
		"banner": { 
			styles:{ 
				root: { 
					"background": recursica['color/surface/default'],
					"stroke": recursica['color/stroke/default'],
					"text": recursica['color-on/surface/high-emphasis'],
					"content-spacing": recursica['size/spacer/2x'],
					"vertical-padding": recursica['size/spacer/2x'],
					"horizontal-padding-xs": "24px",
					"horizontal-padding-sm-m": "80px",
					"horizontal-padding-lg": "128px",
					"horizontal-padding-xl": "232px",
					"text-max-width": "500px" 
				} 
			} 
		},
		"breadcrumb": { 
			styles:{ 
				root: { 
					"clickable": recursica['color-on/background/interactive-text-default'],
					"unclickable": recursica['color-on/background/high-emphasis'],
					"padding": recursica['size/spacer/default'],
					"spacing": recursica['size/spacer/0-5x'],
					"icon-size": "20px" 
				} 
			} 
		},
		"button": { 
			styles:{ 
				root: { 
					"background-contained": recursica['color/interactive/default'],
					"background-contained-hover": recursica['color/interactive/hover'],
					"background-contained-disabled": recursica['color/interactive/disabled'],
					"text-contained-enabled": recursica['color-on/interactive/default'],
					"text-contained-disabled": recursica['color-on/interactive/disabled'],
					"text-enabled-default": recursica['color-on/background/interactive-text-default'],
					"text-hover-default": recursica['color-on/background/interactive-text-hover'],
					"text-disabled-default": recursica['color-on/background/interactive-text-disabled'],
					"border-radius": recursica['size/border-radius/4x'],
					"border-radius-icon": recursica['size/border-radius/3x'],
					"content-max-width": "320px",
					"icon-size": "24px",
					"default-vertical-padding": recursica['size/spacer/1-5x'],
					"default-horizontal-padding": recursica['size/spacer/2x'],
					"default-icon-padding": recursica['size/spacer/1-5x'],
					"default-spacing": recursica['size/spacer/default'],
					"default-min-width": "120px",
					"small-vertical-padding": recursica['size/spacer/0-5x'],
					"small-horizontal-padding": recursica['size/spacer/1-5x'],
					"small-icon-padding": recursica['size/spacer/0-5x'],
					"small-spacing": recursica['size/spacer/0-5x'],
					"small-min-width": "80px" 
				} 
			} 
		},
		"checkbox": { 
			styles:{ 
				root: { 
					"enabled": recursica['color/interactive/default'],
					"disabled": recursica['color/interactive/disabled'],
					"icon-enabled": recursica['color-on/interactive/default'],
					"icon-disabled": recursica['color-on/interactive/disabled'],
					"spacing-stacked": recursica['size/spacer/default'],
					"spacing-inline": recursica['size/spacer/2x'],
					"spacing-individual": recursica['size/spacer/0-5x'],
					"spacing-group": recursica['size/spacer/0-5x'],
					"border-radius": recursica['size/border-radius/0-5x'],
					"checkbox-size": "24px" 
				} 
			} 
		},
		"chip": { 
			styles:{ 
				root: { 
					"text-unselected": recursica['color-on/background/high-emphasis'],
					"stroke-unselected": recursica['color/stroke/default'],
					"text-selected": recursica['color-on/surface/high-emphasis'],
					"stroke-selected": recursica['color/stroke/selected'],
					"background-selected": recursica['color/surface/selected'],
					"stroke-error": recursica['color/stroke/error'],
					"text-error": recursica['color-on/background/alert'],
					"border-radius": recursica['size/spacer/0-5x'],
					"horizontal-padding": recursica['size/spacer/0-5x'],
					"vertical-padding": recursica['size/spacer/default'],
					"spacing": recursica['size/spacer/0-5x'],
					"icon-size": "16px" 
				} 
			} 
		},
		"date-picker": { 
			styles:{ 
				root: { 
					"background": recursica['color/surface/default'],
					"stroke": recursica['color/stroke/default'],
					"background-date-selected": recursica['color/1-scale/default'],
					"date-selected": recursica['color-on/1-scale/default/high-emphasis'],
					"date-default": recursica['color-on/surface/high-emphasis'],
					"date-hover": recursica['color/surface/hover'],
					"date-disabled": recursica['color-on/surface/disabled'],
					"height": "400px",
					"width": "360px",
					"padding": recursica['size/spacer/1-5x'],
					"spacing": recursica['size/spacer/2x'],
					"row-spacing": recursica['size/spacer/default'],
					"button-spacing": recursica['size/spacer/default'],
					"border-radius": recursica['size/border-radius/default'],
					"date-border-radius": recursica['size/border-radius/4x'],
					"date-padding": recursica['size/spacer/0-5x'],
					"date-size": "40px",
					"month-year-height": "40px",
					"month-year-width": "73px" 
				} 
			} 
		},
		"divider": { 
			styles:{ 
				root: { 
					"stroke": recursica['color/stroke/default'] 
				} 
			} 
		},
		"dropdown": { 
			styles:{ 
				root: { 
					"default": recursica['color/stroke/default'],
					"focus": recursica['color/stroke/focused'],
					"selected": recursica['color/stroke/selected'],
					"error": recursica['color/stroke/error'],
					"disabled": recursica['color/stroke/disabled'],
					"background-input": recursica['color/surface/default'],
					"background-input-disabled": recursica['color/surface/disabled'],
					"horizontal-padding": recursica['size/spacer/2x'],
					"vertical-padding": recursica['size/spacer/1-5x'],
					"spacing-stacked": recursica['size/spacer/default'],
					"spacing-inline": recursica['size/spacer/2x'],
					"min-width": "140px",
					"max-width": "464px",
					"input-height": "48px" 
				} 
			} 
		},
		"menu": { 
			styles:{ 
				root: { 
					"surface": recursica['color/surface/default'],
					"menu-vertical-padding": recursica['size/spacer/default'],
					"menu-horizontal-padding": recursica['size/spacer/default'],
					"border-radius": recursica['size/border-radius/default'],
					"min-width": "140px",
					"max-width": "464px" 
				} 
			} 
		},
		"menu-item": { 
			styles:{ 
				root: { 
					"default": recursica['color/surface/default'],
					"selected": recursica['color/surface/selected'],
					"focused": recursica['color/surface/focused'],
					"text-default": recursica['color-on/surface/high-emphasis'],
					"text-disabled": recursica['color-on/surface/disabled'],
					"item-horizontal-padding": recursica['size/spacer/2x'],
					"item-vertical-padding": recursica['size/spacer/2x'],
					"spacing": recursica['size/spacer/default'] 
				} 
			} 
		},
		"file-upload": { 
			styles:{ 
				root: { 
					"background": recursica['color/surface/default'],
					"stroke": recursica['color/1-scale/200'],
					"icon": recursica['color/1-scale/default'],
					"text": recursica['color-on/surface/high-emphasis'],
					"text-labels": recursica['color-on/surface/medium-emphasis'],
					"radius": recursica['size/border-radius/default'],
					"content-spacing": recursica['size/spacer/default'],
					"restrictions-spacing": recursica['size/spacer/0-5x'],
					"vertical-padding": recursica['size/spacer/2x'],
					"horizontal-padding": recursica['size/spacer/2x'],
					"icon-size": "36px" 
				} 
			} 
		},
		"form": { 
			styles:{ 
				root: { 
					"color": recursica['color-on/surface/disabled'],
					"size": recursica['size/spacer/0-5x'] 
				} 
			} 
		},
		"list": { 
			styles:{ 
				root: { 
					"selected-background": recursica['color/background/selected'],
					"text-background": recursica['color-on/background/high-emphasis'],
					"icon-background": recursica['color-on/background/high-emphasis'],
					"selected-surface": recursica['color/surface/selected'],
					"text-surface": recursica['color-on/surface/high-emphasis'],
					"icon-surface": recursica['color-on/surface/high-emphasis'],
					"spacing": recursica['size/spacer/default'],
					"horizontal-padding": recursica['size/spacer/default'],
					"min-height": "44px",
					"min-width": "200px" 
				} 
			} 
		},
		"modal": { 
			styles:{ 
				root: { 
					"background": recursica['color/surface/default'],
					"title": recursica['color-on/surface/high-emphasis'],
					"button-spacing": recursica['size/spacer/0-5x'],
					"border-radius": recursica['size/border-radius/2x'],
					"horizontal-padding": "24px",
					"vertical-padding": "16px",
					"min-width": "304px",
					"max-width": "542px" 
				} 
			} 
		},
		"pagination": { 
			styles:{ 
				root: { 
					"number-spacing": recursica['size/spacer/0-5x'],
					"background-hover-unselected": recursica['color/surface/hover'],
					"background-selected": recursica['color/interactive/default'],
					"background-hover-selected": recursica['color/interactive/hover'],
					"text-default": recursica['color-on/background/interactive-text-default'],
					"text-selected": recursica['color-on/interactive/default'],
					"text-secondary": recursica['color-on/surface/medium-emphasis'],
					"text-disabled": recursica['color-on/background/interactive-text-disabled'] 
				} 
			} 
		},
		"panel": { 
			styles:{ 
				root: { 
					"background": recursica['color/surface/default'],
					"title": recursica['color-on/surface/high-emphasis'],
					"body-padding": "24px",
					"header-horizontal-padding": "24px",
					"header-vertical-padding": recursica['size/spacer/2x'],
					"horizontal-spacing": recursica['size/spacer/2x'] 
				} 
			} 
		},
		"radio": { 
			styles:{ 
				root: { 
					"selected": recursica['color/interactive/default'],
					"selected-disabled": recursica['color/interactive/disabled'],
					"unselected": recursica['color/interactive/default'],
					"unselected-disabled": recursica['color/interactive/disabled'],
					"spacing-stacked": recursica['size/spacer/default'],
					"spacing-inline": recursica['size/spacer/2x'],
					"spacing-individual": recursica['size/spacer/0-5x'],
					"spacing-group": recursica['size/spacer/0-5x'],
					"border-radius": recursica['size/border-radius/2x'],
					"border-radius-inside": recursica['size/border-radius/1-5x'],
					"dot": recursica['size/border-radius/default'],
					"label-vertical-padding": recursica['size/spacer/0-5x'],
					"value-vertical-padding": recursica['size/spacer/0-5x'],
					"width": "24px",
					"height": "24px" 
				} 
			} 
		},
		"search": { 
			styles:{ 
				root: { 
					"stroke-default": recursica['color/stroke/default'],
					"stroke-focus": recursica['color/stroke/focused'],
					"stroke-valued": recursica['color/stroke/selected'],
					"stroke-disabled": recursica['color/stroke/disabled'],
					"background-default": recursica['color/surface/default'],
					"background-disabled": recursica['color/surface/disabled'],
					"horizontal-padding": recursica['size/spacer/2x'],
					"vertical-padding": recursica['size/spacer/1-5x'],
					"spacing-inline": recursica['size/spacer/2x'],
					"radius": recursica['size/border-radius/default'],
					"min-width": "224px",
					"max-width": "464px",
					"input-height": "48px" 
				} 
			} 
		},
		"slider": { 
			styles:{ 
				root: { 
					"track-unselected": recursica['color-on/background/medium-emphasis'],
					"track-unselected-disabled": recursica['color-on/background/disabled'],
					"discrete-steps-default": recursica['color/surface/default'],
					"discrete-steps-disabled": recursica['color/surface/disabled'],
					"track-selected": recursica['color/interactive/default'],
					"track-selected-disabled": recursica['color/interactive/disabled'],
					"handle": recursica['color/interactive/default'],
					"max-width-stacked": "620px",
					"handle-hovered": recursica['color/interactive/hover'],
					"max-width-inline": "874px",
					"handle-disabled": recursica['color/interactive/disabled'],
					"max-width-slider": "464px",
					"min-width-slider": "140px",
					"spacing-stacked": recursica['size/spacer/default'],
					"spacing-inline": recursica['size/spacer/2x'],
					"spacing-content": recursica['size/spacer/2x'],
					"border-radius": recursica['size/border-radius/3x'],
					"track-height": recursica['size/spacer/0-5x'],
					"vertical-padding-discrete-steps": recursica['size/spacer/0-5x'],
					"handle-size": "24px",
					"discrete-step-size": "2px" 
				} 
			} 
		},
		"stepper": { 
			styles:{ 
				root: { 
					"done-step-background": recursica['color/1-scale/default'],
					"done-step-icon": recursica['color-on/1-scale/default/high-emphasis'],
					"active-step-background": recursica['color/surface/default'],
					"active-step-stroke": recursica['color/1-scale/default'],
					"active-step-text": recursica['color-on/surface/high-emphasis'],
					"next-step-enabled-background": recursica['color/surface/default'],
					"next-step-enabled-stroke": recursica['color-on/background/medium-emphasis'],
					"next-step-enabled-text": recursica['color-on/surface/medium-emphasis'],
					"next-step-disabled-background": recursica['color/surface/disabled'],
					"next-step-disabled-stroke": recursica['color-on/background/disabled'],
					"next-step-disabled-text": recursica['color-on/background/disabled'],
					"padding": recursica['size/spacer/0-5x'],
					"border-radius": recursica['size/border-radius/3x'],
					"spacing": recursica['size/spacer/default'],
					"label-spacing": recursica['size/spacer/0-5x'],
					"label-horizontal-padding": recursica['size/spacer/default'],
					"icon-size": "24px",
					"horizontal-min-width": "463px",
					"vertical-min-width": "144px" 
				} 
			} 
		},
		"switch": { 
			styles:{ 
				root: { 
					"thumb-unselected": recursica['color-on/interactive/default'],
					"thumb-unselected-disabled": recursica['color-on/interactive/disabled'],
					"thumb-selected": recursica['color-on/interactive/default'],
					"thumb-selected-disabled": recursica['color-on/interactive/disabled'],
					"track-selected-enabled": recursica['color/interactive/default'],
					"track-selected-disabled": recursica['color/interactive/disabled'],
					"track-unselected-disabled": recursica['color-on/background/disabled'],
					"track-unselected-enabled": recursica['color-on/background/medium-emphasis'],
					"spacing-stacked": recursica['size/spacer/default'],
					"spacing-inline": recursica['size/spacer/2x'],
					"spacing-standalone": recursica['size/spacer/default'],
					"border-radius-track": recursica['size/border-radius/3x'] 
				} 
			} 
		},
		"tab": { 
			styles:{ 
				root: { 
					"default-stroke": recursica['color/stroke/default'],
					"selected-stroke": recursica['color/interactive/default'],
					"unselected": recursica['color-on/background/medium-emphasis'],
					"selected": recursica['color/interactive/default'],
					"horizontal-padding": recursica['size/spacer/2x'],
					"spacing": recursica['size/spacer/default'],
					"icon-size": "20px",
					"height": "48px",
					"min-width": "120px",
					"label-max-width": "200px" 
				} 
			} 
		},
		"table": { 
			styles:{ 
				root: { 
					"cell-background": recursica['color/surface/default'],
					"cell-background-hovered": recursica['color/surface/hover'],
					"cell-background-selected": recursica['color/surface/selected'],
					"header-background": recursica['color/background/default'],
					"header-background-hovered": recursica['color/background/hover'],
					"header-background-pressed": recursica['color/background/pressed'],
					"icon": recursica['color-on/background/medium-emphasis'],
					"action-icon": recursica['color/interactive/default'],
					"spacing": recursica['size/spacer/0-5x'],
					"comfy-height": "64px",
					"comfy-vertical-padding": recursica['size/spacer/2x'],
					"comfy-horizontal-padding": recursica['size/spacer/default'],
					"default-height": "48px",
					"default-vertical-padding": recursica['size/spacer/1-5x'],
					"default-horizontal-padding": recursica['size/spacer/default'],
					"small-height": "40px",
					"small-vertical-padding": recursica['size/spacer/0-5x'],
					"small-horizontal-padding": recursica['size/spacer/default'],
					"header-right-horizontal-padding": recursica['size/spacer/3x'],
					"icon-size": "20px" 
				} 
			} 
		},
		"table-pagination": { 
			styles:{ 
				root: { 
					"text": recursica['color-on/surface/high-emphasis'],
					"stroke": recursica['color/stroke/default'],
					"background": recursica['color/surface/default'],
					"label-spacing": recursica['size/spacer/default'],
					"horizontal-spacing": recursica['size/spacer/2x'],
					"horizontal-padding": recursica['size/spacer/default'],
					"vertical-padding": recursica['size/spacer/2x'],
					"min-width": "700px" 
				} 
			} 
		},
		"text-field": { 
			styles:{ 
				root: { 
					"default": recursica['color/stroke/default'],
					"focused": recursica['color/stroke/focused'],
					"valued": recursica['color/stroke/selected'],
					"error": recursica['color/stroke/error'],
					"disabled": recursica['color/stroke/disabled'],
					"background-input": recursica['color/surface/default'],
					"background-input-disabled": recursica['color/surface/disabled'],
					"horizontal-padding": recursica['size/spacer/2x'],
					"vertical-padding": recursica['size/spacer/1-5x'],
					"spacing-stacked": recursica['size/spacer/default'],
					"spacing-inline": recursica['size/spacer/2x'],
					"min-width": "140px",
					"max-width": "464px",
					"min-input-height": "48px",
					"read-only-background": recursica['color/surface/disabled'],
					"read-only-stroke": recursica['color/stroke/disabled'] 
				} 
			} 
		},
		"time-picker": { 
			styles:{ 
				root: { 
					"max-width-stacked": "288px",
					"stacked-spacing": recursica['size/spacer/default'],
					"max-width-inline": "528px",
					"inline-spacing": recursica['size/spacer/2x'],
					"between-spacing": recursica['size/spacer/default'],
					"help-text-left-vertical-spacing": "240px" 
				} 
			} 
		},
		"toast": { 
			styles:{ 
				root: { 
					"background-default": recursica['color/surface/default'],
					"vertical-padding": recursica['size/spacer/default'],
					"horizontal-padding": recursica['size/spacer/2x'],
					"spacing": recursica['size/spacer/1-5x'],
					"min-width": "384px",
					"max-width": "624px",
					"icon-size": "24px",
					"background-success": recursica['color/success/default'],
					"background-error": recursica['color/alert/default'],
					"text-default": recursica['color-on/surface/high-emphasis'],
					"text-success": recursica['color-on/success/default/high-emphasis'],
					"text-error": recursica['color-on/alert/default/high-emphasis'] 
				} 
			} 
		},
		"tooltip": { 
			styles:{ 
				root: { 
					"background": recursica['color/1-scale/900'],
					"text": recursica['color-on/1-scale/900/high-emphasis'],
					"horizontal-padding": recursica['size/spacer/1-5x'],
					"vertical-padding": recursica['size/spacer/default'],
					"beak-spacer": recursica['size/spacer/default'],
					"radius": recursica['size/border-radius/0-5x'],
					"max-width": "240px" 
				} 
			} 
		}
  },
  colors: {
    "color-on-3-scale-200-high-emphasis": colorsTuple(themeVars['color-on/3-scale/200/high-emphasis']),
		"color-on-surface-success": colorsTuple(themeVars['color-on/surface/success']),
		"color-on-3-scale-600-medium-emphasis": colorsTuple(themeVars['color-on/3-scale/600/medium-emphasis']),
		"color-background-selected": colorsTuple(themeVars['color/background/selected']),
		"color-on-4-scale-200-disabled": colorsTuple(themeVars['color-on/4-scale/200/disabled']),
		"color-on-3-scale-050-disabled": colorsTuple(themeVars['color-on/3-scale/050/disabled']),
		"color-success-400": colorsTuple(themeVars['color/success/400']),
		"color-on-3-scale-700-medium-emphasis": colorsTuple(themeVars['color-on/3-scale/700/medium-emphasis']),
		"color-on-3-scale-900-medium-emphasis": colorsTuple(themeVars['color-on/3-scale/900/medium-emphasis']),
		"color-on-3-scale-700-disabled": colorsTuple(themeVars['color-on/3-scale/700/disabled']),
		"color-surface-pressed": colorsTuple(themeVars['color/surface/pressed']),
		"color-on-4-scale-050-high-emphasis": colorsTuple(themeVars['color-on/4-scale/050/high-emphasis']),
		"color-on-3-scale-100-medium-emphasis": colorsTuple(themeVars['color-on/3-scale/100/medium-emphasis']),
		"color-surface-selected": colorsTuple(themeVars['color/surface/selected']),
		"color-on-3-scale-400-high-emphasis": colorsTuple(themeVars['color-on/3-scale/400/high-emphasis']),
		"color-on-4-scale-200-high-emphasis": colorsTuple(themeVars['color-on/4-scale/200/high-emphasis']),
		"color-background-pressed": colorsTuple(themeVars['color/background/pressed']),
		"color-background-hover": colorsTuple(themeVars['color/background/hover']),
		"color-on-4-scale-300-disabled": colorsTuple(themeVars['color-on/4-scale/300/disabled']),
		"color-on-3-scale-300-high-emphasis": colorsTuple(themeVars['color-on/3-scale/300/high-emphasis']),
		"color-on-4-scale-400-high-emphasis": colorsTuple(themeVars['color-on/4-scale/400/high-emphasis']),
		"color-surface-disabled": colorsTuple(themeVars['color/surface/disabled']),
		"color-on-4-scale-800-disabled": colorsTuple(themeVars['color-on/4-scale/800/disabled']),
		"color-on-surface-disabled": colorsTuple(themeVars['color-on/surface/disabled']),
		"color-on-3-scale-800-disabled": colorsTuple(themeVars['color-on/3-scale/800/disabled']),
		"color-on-4-scale-500-disabled": colorsTuple(themeVars['color-on/4-scale/500/disabled']),
		"color-on-3-scale-100-high-emphasis": colorsTuple(themeVars['color-on/3-scale/100/high-emphasis']),
		"color-on-4-scale-500-medium-emphasis": colorsTuple(themeVars['color-on/4-scale/500/medium-emphasis']),
		"color-on-3-scale-200-disabled": colorsTuple(themeVars['color-on/3-scale/200/disabled']),
		"color-on-3-scale-100-disabled": colorsTuple(themeVars['color-on/3-scale/100/disabled']),
		"color-on-4-scale-500-high-emphasis": colorsTuple(themeVars['color-on/4-scale/500/high-emphasis']),
		"color-on-surface-interactive-text-focused": colorsTuple(themeVars['color-on/surface/interactive-text-focused']),
		"color-on-success-700-disabled": colorsTuple(themeVars['color-on/success/700/disabled']),
		"color-surface-focused": colorsTuple(themeVars['color/surface/focused']),
		"color-on-3-scale-600-high-emphasis": colorsTuple(themeVars['color-on/3-scale/600/high-emphasis']),
		"color-on-4-scale-600-disabled": colorsTuple(themeVars['color-on/4-scale/600/disabled']),
		"color-on-3-scale-500-high-emphasis": colorsTuple(themeVars['color-on/3-scale/500/high-emphasis']),
		"color-on-4-scale-600-medium-emphasis": colorsTuple(themeVars['color-on/4-scale/600/medium-emphasis']),
		"color-on-4-scale-700-disabled": colorsTuple(themeVars['color-on/4-scale/700/disabled']),
		"color-on-3-scale-500-disabled": colorsTuple(themeVars['color-on/3-scale/500/disabled']),
		"color-on-4-scale-700-medium-emphasis": colorsTuple(themeVars['color-on/4-scale/700/medium-emphasis']),
		"color-on-3-scale-500-medium-emphasis": colorsTuple(themeVars['color-on/3-scale/500/medium-emphasis']),
		"color-1-scale-default": colorsTuple(themeVars['color/1-scale/default']),
		"color-on-3-scale-600-disabled": colorsTuple(themeVars['color-on/3-scale/600/disabled']),
		"color-on-4-scale-600-high-emphasis": colorsTuple(themeVars['color-on/4-scale/600/high-emphasis']),
		"color-on-4-scale-700-high-emphasis": colorsTuple(themeVars['color-on/4-scale/700/high-emphasis']),
		"color-on-3-scale-900-high-emphasis": colorsTuple(themeVars['color-on/3-scale/900/high-emphasis']),
		"color-on-3-scale-900-disabled": colorsTuple(themeVars['color-on/3-scale/900/disabled']),
		"color-on-4-scale-800-medium-emphasis": colorsTuple(themeVars['color-on/4-scale/800/medium-emphasis']),
		"color-stroke-default": colorsTuple(themeVars['color/stroke/default']),
		"color-on-4-scale-800-high-emphasis": colorsTuple(themeVars['color-on/4-scale/800/high-emphasis']),
		"color-on-3-scale-400-disabled": colorsTuple(themeVars['color-on/3-scale/400/disabled']),
		"color-on-3-scale-300-disabled": colorsTuple(themeVars['color-on/3-scale/300/disabled']),
		"color-on-4-scale-900-disabled": colorsTuple(themeVars['color-on/4-scale/900/disabled']),
		"color-on-3-scale-300-medium-emphasis": colorsTuple(themeVars['color-on/3-scale/300/medium-emphasis']),
		"color-on-4-scale-900-medium-emphasis": colorsTuple(themeVars['color-on/4-scale/900/medium-emphasis']),
		"color-on-3-scale-200-medium-emphasis": colorsTuple(themeVars['color-on/3-scale/200/medium-emphasis']),
		"color-on-4-scale-900-high-emphasis": colorsTuple(themeVars['color-on/4-scale/900/high-emphasis']),
		"color-on-surface-alert": colorsTuple(themeVars['color-on/surface/alert']),
		"color-on-background-success": colorsTuple(themeVars['color-on/background/success']),
		"color-on-surface-interactive-text-pressed": colorsTuple(themeVars['color-on/surface/interactive-text-pressed']),
		"color-on-background-alert": colorsTuple(themeVars['color-on/background/alert']),
		"color-on-surface-interactive-text-default": colorsTuple(themeVars['color-on/surface/interactive-text-default']),
		"color-on-success-700-medium-emphasis": colorsTuple(themeVars['color-on/success/700/medium-emphasis']),
		"color-surface-hover": colorsTuple(themeVars['color/surface/hover']),
		"color-on-3-scale-050-medium-emphasis": colorsTuple(themeVars['color-on/3-scale/050/medium-emphasis']),
		"color-on-4-scale-100-disabled": colorsTuple(themeVars['color-on/4-scale/100/disabled']),
		"color-on-success-700-high-emphasis": colorsTuple(themeVars['color-on/success/700/high-emphasis']),
		"color-on-4-scale-100-medium-emphasis": colorsTuple(themeVars['color-on/4-scale/100/medium-emphasis']),
		"color-on-3-scale-050-high-emphasis": colorsTuple(themeVars['color-on/3-scale/050/high-emphasis']),
		"color-on-1-scale-300-high-emphasis": colorsTuple(themeVars['color-on/1-scale/300/high-emphasis']),
		"color-on-1-scale-300-medium-emphasis": colorsTuple(themeVars['color-on/1-scale/300/medium-emphasis']),
		"color-2-scale-100": colorsTuple(themeVars['color/2-scale/100']),
		"color-2-scale-200": colorsTuple(themeVars['color/2-scale/200']),
		"color-2-scale-300": colorsTuple(themeVars['color/2-scale/300']),
		"color-2-scale-400": colorsTuple(themeVars['color/2-scale/400']),
		"color-2-scale-500": colorsTuple(themeVars['color/2-scale/500']),
		"color-2-scale-600": colorsTuple(themeVars['color/2-scale/600']),
		"color-2-scale-900": colorsTuple(themeVars['color/2-scale/900']),
		"color-on-3-scale-400-medium-emphasis": colorsTuple(themeVars['color-on/3-scale/400/medium-emphasis']),
		"color-on-4-scale-200-medium-emphasis": colorsTuple(themeVars['color-on/4-scale/200/medium-emphasis']),
		"color-on-4-scale-100-high-emphasis": colorsTuple(themeVars['color-on/4-scale/100/high-emphasis']),
		"color-on-4-scale-050-disabled": colorsTuple(themeVars['color-on/4-scale/050/disabled']),
		"color-on-4-scale-050-medium-emphasis": colorsTuple(themeVars['color-on/4-scale/050/medium-emphasis']),
		"color-2-scale-50": colorsTuple(themeVars['color/2-scale/50']),
		"color-on-surface-medium-emphasis": colorsTuple(themeVars['color-on/surface/medium-emphasis']),
		"color-on-background-disabled": colorsTuple(themeVars['color-on/background/disabled']),
		"color-on-background-high-emphasis": colorsTuple(themeVars['color-on/background/high-emphasis']),
		"color-on-3-scale-700-high-emphasis": colorsTuple(themeVars['color-on/3-scale/700/high-emphasis']),
		"color-on-1-scale-300-disabled": colorsTuple(themeVars['color-on/1-scale/300/disabled']),
		"color-background-disabled": colorsTuple(themeVars['color/background/disabled']),
		"color-on-1-scale-050-disabled": colorsTuple(themeVars['color-on/1-scale/050/disabled']),
		"color-surface-default": colorsTuple(themeVars['color/surface/default']),
		"color-on-1-scale-050-medium-emphasis": colorsTuple(themeVars['color-on/1-scale/050/medium-emphasis']),
		"color-on-1-scale-200-disabled": colorsTuple(themeVars['color-on/1-scale/200/disabled']),
		"color-on-1-scale-200-medium-emphasis": colorsTuple(themeVars['color-on/1-scale/200/medium-emphasis']),
		"color-on-1-scale-200-high-emphasis": colorsTuple(themeVars['color-on/1-scale/200/high-emphasis']),
		"color-on-1-scale-400-medium-emphasis": colorsTuple(themeVars['color-on/1-scale/400/medium-emphasis']),
		"color-on-1-scale-100-high-emphasis": colorsTuple(themeVars['color-on/1-scale/100/high-emphasis']),
		"color-on-1-scale-400-high-emphasis": colorsTuple(themeVars['color-on/1-scale/400/high-emphasis']),
		"color-1-scale-900": colorsTuple(themeVars['color/1-scale/900']),
		"color-on-1-scale-500-disabled": colorsTuple(themeVars['color-on/1-scale/500/disabled']),
		"color-on-1-scale-500-medium-emphasis": colorsTuple(themeVars['color-on/1-scale/500/medium-emphasis']),
		"color-on-1-scale-600-disabled": colorsTuple(themeVars['color-on/1-scale/600/disabled']),
		"color-on-1-scale-600-medium-emphasis": colorsTuple(themeVars['color-on/1-scale/600/medium-emphasis']),
		"color-on-1-scale-600-high-emphasis": colorsTuple(themeVars['color-on/1-scale/600/high-emphasis']),
		"color-1-scale-800": colorsTuple(themeVars['color/1-scale/800']),
		"color-on-1-scale-700-disabled": colorsTuple(themeVars['color-on/1-scale/700/disabled']),
		"color-on-1-scale-700-medium-emphasis": colorsTuple(themeVars['color-on/1-scale/700/medium-emphasis']),
		"color-on-surface-interactive-text-hover": colorsTuple(themeVars['color-on/surface/interactive-text-hover']),
		"color-2-scale-800": colorsTuple(themeVars['color/2-scale/800']),
		"color-background-default": colorsTuple(themeVars['color/background/default']),
		"color-on-1-scale-800-disabled": colorsTuple(themeVars['color-on/1-scale/800/disabled']),
		"color-on-1-scale-800-medium-emphasis": colorsTuple(themeVars['color-on/1-scale/800/medium-emphasis']),
		"color-1-scale-400": colorsTuple(themeVars['color/1-scale/400']),
		"color-on-1-scale-900-medium-emphasis": colorsTuple(themeVars['color-on/1-scale/900/medium-emphasis']),
		"color-1-scale-500": colorsTuple(themeVars['color/1-scale/500']),
		"color-on-1-scale-900-high-emphasis": colorsTuple(themeVars['color-on/1-scale/900/high-emphasis']),
		"color-on-1-scale-500-high-emphasis": colorsTuple(themeVars['color-on/1-scale/500/high-emphasis']),
		"color-1-scale-700": colorsTuple(themeVars['color/1-scale/700']),
		"color-on-1-scale-100-disabled": colorsTuple(themeVars['color-on/1-scale/100/disabled']),
		"color-on-4-scale-400-disabled": colorsTuple(themeVars['color-on/4-scale/400/disabled']),
		"color-1-scale-50": colorsTuple(themeVars['color/1-scale/50']),
		"color-on-1-scale-050-high-emphasis": colorsTuple(themeVars['color-on/1-scale/050/high-emphasis']),
		"color-on-4-scale-400-medium-emphasis": colorsTuple(themeVars['color-on/4-scale/400/medium-emphasis']),
		"color-1-scale-100": colorsTuple(themeVars['color/1-scale/100']),
		"color-background-focused": colorsTuple(themeVars['color/background/focused']),
		"color-on-1-scale-900-disabled": colorsTuple(themeVars['color-on/1-scale/900/disabled']),
		"color-on-1-scale-800-high-emphasis": colorsTuple(themeVars['color-on/1-scale/800/high-emphasis']),
		"color-on-4-scale-300-medium-emphasis": colorsTuple(themeVars['color-on/4-scale/300/medium-emphasis']),
		"color-1-scale-200": colorsTuple(themeVars['color/1-scale/200']),
		"color-on-background-medium-emphasis": colorsTuple(themeVars['color-on/background/medium-emphasis']),
		"color-on-3-scale-800-high-emphasis": colorsTuple(themeVars['color-on/3-scale/800/high-emphasis']),
		"color-1-scale-600": colorsTuple(themeVars['color/1-scale/600']),
		"color-on-1-scale-400-disabled": colorsTuple(themeVars['color-on/1-scale/400/disabled']),
		"color-on-3-scale-800-medium-emphasis": colorsTuple(themeVars['color-on/3-scale/800/medium-emphasis']),
		"color-2-scale-700": colorsTuple(themeVars['color/2-scale/700']),
		"color-on-1-scale-700-high-emphasis": colorsTuple(themeVars['color-on/1-scale/700/high-emphasis']),
		"color-on-surface-high-emphasis": colorsTuple(themeVars['color-on/surface/high-emphasis']),
		"color-on-1-scale-100-medium-emphasis": colorsTuple(themeVars['color-on/1-scale/100/medium-emphasis']),
		"color-on-4-scale-300-high-emphasis": colorsTuple(themeVars['color-on/4-scale/300/high-emphasis']),
		"color-1-scale-300": colorsTuple(themeVars['color/1-scale/300']),
		"color-on-2-scale-200-disabled": colorsTuple(themeVars['color-on/2-scale/200/disabled']),
		"color-on-2-scale-300-disabled": colorsTuple(themeVars['color-on/2-scale/300/disabled']),
		"color-on-2-scale-300-medium-emphasis": colorsTuple(themeVars['color-on/2-scale/300/medium-emphasis']),
		"color-on-2-scale-200-high-emphasis": colorsTuple(themeVars['color-on/2-scale/200/high-emphasis']),
		"color-on-2-scale-900-disabled": colorsTuple(themeVars['color-on/2-scale/900/disabled']),
		"color-on-2-scale-200-medium-emphasis": colorsTuple(themeVars['color-on/2-scale/200/medium-emphasis']),
		"color-on-2-scale-900-medium-emphasis": colorsTuple(themeVars['color-on/2-scale/900/medium-emphasis']),
		"color-on-2-scale-400-medium-emphasis": colorsTuple(themeVars['color-on/2-scale/400/medium-emphasis']),
		"color-on-2-scale-800-disabled": colorsTuple(themeVars['color-on/2-scale/800/disabled']),
		"color-on-2-scale-700-high-emphasis": colorsTuple(themeVars['color-on/2-scale/700/high-emphasis']),
		"color-on-2-scale-700-medium-emphasis": colorsTuple(themeVars['color-on/2-scale/700/medium-emphasis']),
		"color-on-2-scale-700-disabled": colorsTuple(themeVars['color-on/2-scale/700/disabled']),
		"color-on-2-scale-900-high-emphasis": colorsTuple(themeVars['color-on/2-scale/900/high-emphasis']),
		"color-on-2-scale-100-high-emphasis": colorsTuple(themeVars['color-on/2-scale/100/high-emphasis']),
		"color-on-2-scale-100-medium-emphasis": colorsTuple(themeVars['color-on/2-scale/100/medium-emphasis']),
		"color-on-2-scale-600-high-emphasis": colorsTuple(themeVars['color-on/2-scale/600/high-emphasis']),
		"color-on-2-scale-800-high-emphasis": colorsTuple(themeVars['color-on/2-scale/800/high-emphasis']),
		"color-on-2-scale-800-medium-emphasis": colorsTuple(themeVars['color-on/2-scale/800/medium-emphasis']),
		"color-on-2-scale-100-disabled": colorsTuple(themeVars['color-on/2-scale/100/disabled']),
		"color-on-2-scale-400-disabled": colorsTuple(themeVars['color-on/2-scale/400/disabled']),
		"color-on-2-scale-300-high-emphasis": colorsTuple(themeVars['color-on/2-scale/300/high-emphasis']),
		"color-on-2-scale-500-high-emphasis": colorsTuple(themeVars['color-on/2-scale/500/high-emphasis']),
		"color-on-2-scale-500-medium-emphasis": colorsTuple(themeVars['color-on/2-scale/500/medium-emphasis']),
		"color-on-2-scale-500-disabled": colorsTuple(themeVars['color-on/2-scale/500/disabled']),
		"color-on-2-scale-400-high-emphasis": colorsTuple(themeVars['color-on/2-scale/400/high-emphasis']),
		"color-on-2-scale-600-medium-emphasis": colorsTuple(themeVars['color-on/2-scale/600/medium-emphasis']),
		"color-on-2-scale-600-disabled": colorsTuple(themeVars['color-on/2-scale/600/disabled']),
		"color-2-scale-default": colorsTuple(themeVars['color/2-scale/default']),
		"color-on-success-100-high-emphasis": colorsTuple(themeVars['color-on/success/100/high-emphasis']),
		"color-on-alert-500-medium-emphasis": colorsTuple(themeVars['color-on/alert/500/medium-emphasis']),
		"color-on-success-200-disabled": colorsTuple(themeVars['color-on/success/200/disabled']),
		"color-on-alert-500-disabled": colorsTuple(themeVars['color-on/alert/500/disabled']),
		"color-on-alert-700-high-emphasis": colorsTuple(themeVars['color-on/alert/700/high-emphasis']),
		"color-on-success-300-high-emphasis": colorsTuple(themeVars['color-on/success/300/high-emphasis']),
		"color-on-alert-900-high-emphasis": colorsTuple(themeVars['color-on/alert/900/high-emphasis']),
		"color-on-success-300-medium-emphasis": colorsTuple(themeVars['color-on/success/300/medium-emphasis']),
		"color-on-success-300-disabled": colorsTuple(themeVars['color-on/success/300/disabled']),
		"color-on-success-050-medium-emphasis": colorsTuple(themeVars['color-on/success/050/medium-emphasis']),
		"color-on-warning-050-disabled": colorsTuple(themeVars['color-on/warning/050/disabled']),
		"color-on-success-050-high-emphasis": colorsTuple(themeVars['color-on/success/050/high-emphasis']),
		"color-warning-700": colorsTuple(themeVars['color/warning/700']),
		"color-on-success-100-medium-emphasis": colorsTuple(themeVars['color-on/success/100/medium-emphasis']),
		"color-on-success-200-medium-emphasis": colorsTuple(themeVars['color-on/success/200/medium-emphasis']),
		"color-on-success-200-high-emphasis": colorsTuple(themeVars['color-on/success/200/high-emphasis']),
		"color-on-warning-050-medium-emphasis": colorsTuple(themeVars['color-on/warning/050/medium-emphasis']),
		"color-on-success-400-disabled": colorsTuple(themeVars['color-on/success/400/disabled']),
		"color-on-success-500-medium-emphasis": colorsTuple(themeVars['color-on/success/500/medium-emphasis']),
		"color-warning-50": colorsTuple(themeVars['color/warning/50']),
		"color-on-success-600-disabled": colorsTuple(themeVars['color-on/success/600/disabled']),
		"color-warning-300": colorsTuple(themeVars['color/warning/300']),
		"color-on-warning-100-disabled": colorsTuple(themeVars['color-on/warning/100/disabled']),
		"color-on-success-500-disabled": colorsTuple(themeVars['color-on/success/500/disabled']),
		"color-on-success-600-medium-emphasis": colorsTuple(themeVars['color-on/success/600/medium-emphasis']),
		"color-warning-400": colorsTuple(themeVars['color/warning/400']),
		"color-on-alert-700-disabled": colorsTuple(themeVars['color-on/alert/700/disabled']),
		"color-on-alert-050-disabled": colorsTuple(themeVars['color-on/alert/050/disabled']),
		"color-warning-200": colorsTuple(themeVars['color/warning/200']),
		"color-on-success-500-high-emphasis": colorsTuple(themeVars['color-on/success/500/high-emphasis']),
		"color-on-alert-100-disabled": colorsTuple(themeVars['color-on/alert/100/disabled']),
		"color-success-200": colorsTuple(themeVars['color/success/200']),
		"color-on-alert-050-medium-emphasis": colorsTuple(themeVars['color-on/alert/050/medium-emphasis']),
		"color-on-alert-200-medium-emphasis": colorsTuple(themeVars['color-on/alert/200/medium-emphasis']),
		"color-on-alert-200-high-emphasis": colorsTuple(themeVars['color-on/alert/200/high-emphasis']),
		"color-on-alert-300-disabled": colorsTuple(themeVars['color-on/alert/300/disabled']),
		"color-success-900": colorsTuple(themeVars['color/success/900']),
		"color-on-success-900-high-emphasis": colorsTuple(themeVars['color-on/success/900/high-emphasis']),
		"color-on-alert-300-medium-emphasis": colorsTuple(themeVars['color-on/alert/300/medium-emphasis']),
		"color-on-alert-300-high-emphasis": colorsTuple(themeVars['color-on/alert/300/high-emphasis']),
		"color-on-alert-400-disabled": colorsTuple(themeVars['color-on/alert/400/disabled']),
		"color-on-alert-400-medium-emphasis": colorsTuple(themeVars['color-on/alert/400/medium-emphasis']),
		"color-on-alert-400-high-emphasis": colorsTuple(themeVars['color-on/alert/400/high-emphasis']),
		"color-on-alert-500-high-emphasis": colorsTuple(themeVars['color-on/alert/500/high-emphasis']),
		"color-on-alert-600-disabled": colorsTuple(themeVars['color-on/alert/600/disabled']),
		"color-alert-600": colorsTuple(themeVars['color/alert/600']),
		"color-on-warning-050-high-emphasis": colorsTuple(themeVars['color-on/warning/050/high-emphasis']),
		"color-on-alert-800-disabled": colorsTuple(themeVars['color-on/alert/800/disabled']),
		"color-on-alert-900-disabled": colorsTuple(themeVars['color-on/alert/900/disabled']),
		"color-on-warning-300-medium-emphasis": colorsTuple(themeVars['color-on/warning/300/medium-emphasis']),
		"color-on-warning-500-high-emphasis": colorsTuple(themeVars['color-on/warning/500/high-emphasis']),
		"color-warning-100": colorsTuple(themeVars['color/warning/100']),
		"color-on-alert-200-disabled": colorsTuple(themeVars['color-on/alert/200/disabled']),
		"color-success-800": colorsTuple(themeVars['color/success/800']),
		"color-on-warning-600-medium-emphasis": colorsTuple(themeVars['color-on/warning/600/medium-emphasis']),
		"color-on-warning-700-disabled": colorsTuple(themeVars['color-on/warning/700/disabled']),
		"color-on-alert-100-medium-emphasis": colorsTuple(themeVars['color-on/alert/100/medium-emphasis']),
		"color-success-300": colorsTuple(themeVars['color/success/300']),
		"color-on-alert-050-high-emphasis": colorsTuple(themeVars['color-on/alert/050/high-emphasis']),
		"color-on-warning-600-disabled": colorsTuple(themeVars['color-on/warning/600/disabled']),
		"color-on-alert-100-high-emphasis": colorsTuple(themeVars['color-on/alert/100/high-emphasis']),
		"color-success-700": colorsTuple(themeVars['color/success/700']),
		"color-on-warning-400-disabled": colorsTuple(themeVars['color-on/warning/400/disabled']),
		"color-warning-600": colorsTuple(themeVars['color/warning/600']),
		"color-warning-500": colorsTuple(themeVars['color/warning/500']),
		"color-on-success-100-disabled": colorsTuple(themeVars['color-on/success/100/disabled']),
		"color-on-alert-700-medium-emphasis": colorsTuple(themeVars['color-on/alert/700/medium-emphasis']),
		"color-warning-800": colorsTuple(themeVars['color/warning/800']),
		"color-on-warning-800-high-emphasis": colorsTuple(themeVars['color-on/warning/800/high-emphasis']),
		"color-on-warning-900-high-emphasis": colorsTuple(themeVars['color-on/warning/900/high-emphasis']),
		"color-on-warning-600-high-emphasis": colorsTuple(themeVars['color-on/warning/600/high-emphasis']),
		"color-on-warning-700-high-emphasis": colorsTuple(themeVars['color-on/warning/700/high-emphasis']),
		"color-on-warning-700-medium-emphasis": colorsTuple(themeVars['color-on/warning/700/medium-emphasis']),
		"color-on-warning-800-medium-emphasis": colorsTuple(themeVars['color-on/warning/800/medium-emphasis']),
		"color-on-warning-800-disabled": colorsTuple(themeVars['color-on/warning/800/disabled']),
		"color-on-warning-300-high-emphasis": colorsTuple(themeVars['color-on/warning/300/high-emphasis']),
		"color-on-warning-400-medium-emphasis": colorsTuple(themeVars['color-on/warning/400/medium-emphasis']),
		"color-on-warning-900-medium-emphasis": colorsTuple(themeVars['color-on/warning/900/medium-emphasis']),
		"color-on-success-600-high-emphasis": colorsTuple(themeVars['color-on/success/600/high-emphasis']),
		"color-on-success-400-medium-emphasis": colorsTuple(themeVars['color-on/success/400/medium-emphasis']),
		"color-on-success-400-high-emphasis": colorsTuple(themeVars['color-on/success/400/high-emphasis']),
		"color-on-success-050-disabled": colorsTuple(themeVars['color-on/success/050/disabled']),
		"color-on-warning-100-high-emphasis": colorsTuple(themeVars['color-on/warning/100/high-emphasis']),
		"color-alert-700": colorsTuple(themeVars['color/alert/700']),
		"color-alert-50": colorsTuple(themeVars['color/alert/50']),
		"color-alert-100": colorsTuple(themeVars['color/alert/100']),
		"color-on-warning-900-disabled": colorsTuple(themeVars['color-on/warning/900/disabled']),
		"color-alert-500": colorsTuple(themeVars['color/alert/500']),
		"color-on-warning-200-high-emphasis": colorsTuple(themeVars['color-on/warning/200/high-emphasis']),
		"color-alert-400": colorsTuple(themeVars['color/alert/400']),
		"color-on-alert-600-high-emphasis": colorsTuple(themeVars['color-on/alert/600/high-emphasis']),
		"color-on-alert-600-medium-emphasis": colorsTuple(themeVars['color-on/alert/600/medium-emphasis']),
		"color-on-alert-800-high-emphasis": colorsTuple(themeVars['color-on/alert/800/high-emphasis']),
		"color-on-alert-900-medium-emphasis": colorsTuple(themeVars['color-on/alert/900/medium-emphasis']),
		"color-on-success-900-disabled": colorsTuple(themeVars['color-on/success/900/disabled']),
		"color-on-success-900-medium-emphasis": colorsTuple(themeVars['color-on/success/900/medium-emphasis']),
		"color-success-600": colorsTuple(themeVars['color/success/600']),
		"color-on-success-800-high-emphasis": colorsTuple(themeVars['color-on/success/800/high-emphasis']),
		"color-on-warning-200-disabled": colorsTuple(themeVars['color-on/warning/200/disabled']),
		"color-alert-200": colorsTuple(themeVars['color/alert/200']),
		"color-on-warning-300-disabled": colorsTuple(themeVars['color-on/warning/300/disabled']),
		"color-alert-300": colorsTuple(themeVars['color/alert/300']),
		"color-on-success-800-disabled": colorsTuple(themeVars['color-on/success/800/disabled']),
		"color-warning-900": colorsTuple(themeVars['color/warning/900']),
		"color-success-50": colorsTuple(themeVars['color/success/50']),
		"color-on-warning-400-high-emphasis": colorsTuple(themeVars['color-on/warning/400/high-emphasis']),
		"color-on-alert-800-medium-emphasis": colorsTuple(themeVars['color-on/alert/800/medium-emphasis']),
		"color-success-500": colorsTuple(themeVars['color/success/500']),
		"color-on-success-800-medium-emphasis": colorsTuple(themeVars['color-on/success/800/medium-emphasis']),
		"color-on-warning-500-disabled": colorsTuple(themeVars['color-on/warning/500/disabled']),
		"color-on-warning-500-medium-emphasis": colorsTuple(themeVars['color-on/warning/500/medium-emphasis']),
		"color-on-warning-100-medium-emphasis": colorsTuple(themeVars['color-on/warning/100/medium-emphasis']),
		"color-alert-800": colorsTuple(themeVars['color/alert/800']),
		"color-on-warning-200-medium-emphasis": colorsTuple(themeVars['color-on/warning/200/medium-emphasis']),
		"color-alert-900": colorsTuple(themeVars['color/alert/900']),
		"color-success-100": colorsTuple(themeVars['color/success/100']),
		"color-alert-default": colorsTuple(themeVars['color/alert/default']),
		"color-on-1-scale-default-high-emphasis": colorsTuple(themeVars['color-on/1-scale/default/high-emphasis']),
		"color-on-alert-default-high-emphasis": colorsTuple(themeVars['color-on/alert/default/high-emphasis']),
		"color-on-1-scale-default-disabled": colorsTuple(themeVars['color-on/1-scale/default/disabled']),
		"color-on-alert-default-medium-emphasis": colorsTuple(themeVars['color-on/alert/default/medium-emphasis']),
		"color-on-alert-default-disabled": colorsTuple(themeVars['color-on/alert/default/disabled']),
		"color-success-default": colorsTuple(themeVars['color/success/default']),
		"color-on-success-default-high-emphasis": colorsTuple(themeVars['color-on/success/default/high-emphasis']),
		"color-on-success-default-medium-emphasis": colorsTuple(themeVars['color-on/success/default/medium-emphasis']),
		"color-on-success-default-disabled": colorsTuple(themeVars['color-on/success/default/disabled']),
		"color-on-1-scale-default-medium-emphasis": colorsTuple(themeVars['color-on/1-scale/default/medium-emphasis']),
		"color-on-2-scale-050-high-emphasis": colorsTuple(themeVars['color-on/2-scale/050/high-emphasis']),
		"color-on-2-scale-050-medium-emphasis": colorsTuple(themeVars['color-on/2-scale/050/medium-emphasis']),
		"color-on-2-scale-050-disabled": colorsTuple(themeVars['color-on/2-scale/050/disabled']),
		"color-warning-default": colorsTuple(themeVars['color/warning/default']),
		"color-on-2-scale-default-disabled": colorsTuple(themeVars['color-on/2-scale/default/disabled']),
		"color-on-2-scale-default-medium-emphasis": colorsTuple(themeVars['color-on/2-scale/default/medium-emphasis']),
		"color-on-2-scale-default-high-emphasis": colorsTuple(themeVars['color-on/2-scale/default/high-emphasis']),
		"color-interactive-selected": colorsTuple(themeVars['color/interactive/selected']),
		"color-interactive-focused": colorsTuple(themeVars['color/interactive/focused']),
		"color-interactive-disabled": colorsTuple(themeVars['color/interactive/disabled']),
		"color-on-surface-interactive-text-selected": colorsTuple(themeVars['color-on/surface/interactive-text-selected']),
		"color-interactive-default": colorsTuple(themeVars['color/interactive/default']),
		"color-interactive-hover": colorsTuple(themeVars['color/interactive/hover']),
		"color-on-surface-interactive-text-disabled": colorsTuple(themeVars['color-on/surface/interactive-text-disabled']),
		"color-interactive-pressed": colorsTuple(themeVars['color/interactive/pressed']),
		"color-4-scale-100": colorsTuple(themeVars['color/4-scale/100']),
		"color-4-scale-200": colorsTuple(themeVars['color/4-scale/200']),
		"color-4-scale-500": colorsTuple(themeVars['color/4-scale/500']),
		"color-4-scale-300": colorsTuple(themeVars['color/4-scale/300']),
		"color-4-scale-400": colorsTuple(themeVars['color/4-scale/400']),
		"color-4-scale-700": colorsTuple(themeVars['color/4-scale/700']),
		"color-3-scale-50": colorsTuple(themeVars['color/3-scale/50']),
		"color-4-scale-800": colorsTuple(themeVars['color/4-scale/800']),
		"color-4-scale-600": colorsTuple(themeVars['color/4-scale/600']),
		"color-3-scale-200": colorsTuple(themeVars['color/3-scale/200']),
		"color-3-scale-300": colorsTuple(themeVars['color/3-scale/300']),
		"color-3-scale-400": colorsTuple(themeVars['color/3-scale/400']),
		"color-3-scale-500": colorsTuple(themeVars['color/3-scale/500']),
		"color-3-scale-600": colorsTuple(themeVars['color/3-scale/600']),
		"color-3-scale-100": colorsTuple(themeVars['color/3-scale/100']),
		"color-4-scale-900": colorsTuple(themeVars['color/4-scale/900']),
		"color-3-scale-800": colorsTuple(themeVars['color/3-scale/800']),
		"color-3-scale-700": colorsTuple(themeVars['color/3-scale/700']),
		"color-4-scale-50": colorsTuple(themeVars['color/4-scale/50']),
		"color-3-scale-900": colorsTuple(themeVars['color/3-scale/900']),
		"color-on-background-interactive-text-disabled": colorsTuple(themeVars['color-on/background/interactive-text-disabled']),
		"color-on-background-interactive-text-hover": colorsTuple(themeVars['color-on/background/interactive-text-hover']),
		"color-on-background-interactive-text-default": colorsTuple(themeVars['color-on/background/interactive-text-default']),
		"color-on-background-interactive-text-focused": colorsTuple(themeVars['color-on/background/interactive-text-focused']),
		"color-on-background-interactive-text-selected": colorsTuple(themeVars['color-on/background/interactive-text-selected']),
		"color-on-background-interactive-text-pressed": colorsTuple(themeVars['color-on/background/interactive-text-pressed']),
		"color-neutral-900": colorsTuple(themeVars['color/neutral/900']),
		"color-neutral-100": colorsTuple(themeVars['color/neutral/100']),
		"color-neutral-700": colorsTuple(themeVars['color/neutral/700']),
		"color-neutral-400": colorsTuple(themeVars['color/neutral/400']),
		"color-neutral-800": colorsTuple(themeVars['color/neutral/800']),
		"color-neutral-600": colorsTuple(themeVars['color/neutral/600']),
		"color-neutral-500": colorsTuple(themeVars['color/neutral/500']),
		"color-neutral-300": colorsTuple(themeVars['color/neutral/300']),
		"color-neutral-200": colorsTuple(themeVars['color/neutral/200']),
		"color-neutral-50": colorsTuple(themeVars['color/neutral/50']),
		"color-on-interactive-disabled": colorsTuple(themeVars['color-on/interactive/disabled']),
		"color-on-interactive-default": colorsTuple(themeVars['color-on/interactive/default']),
		"color-stroke-pressed": colorsTuple(themeVars['color/stroke/pressed']),
		"color-stroke-focused": colorsTuple(themeVars['color/stroke/focused']),
		"color-stroke-selected": colorsTuple(themeVars['color/stroke/selected']),
		"color-stroke-hover": colorsTuple(themeVars['color/stroke/hover']),
		"color-stroke-disabled": colorsTuple(themeVars['color/stroke/disabled']),
		"color-stroke-error": colorsTuple(themeVars['color/stroke/error']),
		"color-on-alert-default-interactive-text-pressed": colorsTuple(themeVars['color-on/alert/default/interactive-text-pressed']),
		"color-on-1-scale-default-interactive-text-hover": colorsTuple(themeVars['color-on/1-scale/default/interactive-text-hover']),
		"color-on-alert-default-interactive-text-default": colorsTuple(themeVars['color-on/alert/default/interactive-text-default']),
		"color-on-1-scale-default-interactive-text-pressed": colorsTuple(themeVars['color-on/1-scale/default/interactive-text-pressed']),
		"color-on-success-default-interactive-text-selected": colorsTuple(themeVars['color-on/success/default/interactive-text-selected']),
		"color-on-success-default-interactive-text-focused": colorsTuple(themeVars['color-on/success/default/interactive-text-focused']),
		"color-on-success-default-action-text-disabled": colorsTuple(themeVars['color-on/success/default/action-text-disabled']),
		"color-on-alert-default-interactive-text-disabled": colorsTuple(themeVars['color-on/alert/default/interactive-text-disabled']),
		"color-on-success-default-interactive-text-pressed": colorsTuple(themeVars['color-on/success/default/interactive-text-pressed']),
		"color-on-success-default-interactive-text-hover": colorsTuple(themeVars['color-on/success/default/interactive-text-hover']),
		"color-on-1-scale-default-interactive-text-focused": colorsTuple(themeVars['color-on/1-scale/default/interactive-text-focused']),
		"color-on-success-default-interactive-text-default": colorsTuple(themeVars['color-on/success/default/interactive-text-default']),
		"color-on-1-scale-default-action-text-disabled": colorsTuple(themeVars['color-on/1-scale/default/action-text-disabled']),
		"color-on-1-scale-default-interactive-text-selected": colorsTuple(themeVars['color-on/1-scale/default/interactive-text-selected']),
		"color-on-alert-default-interactive-text-selected": colorsTuple(themeVars['color-on/alert/default/interactive-text-selected']),
		"color-on-alert-default-interactive-text-focused": colorsTuple(themeVars['color-on/alert/default/interactive-text-focused']),
		"color-on-alert-default-interactive-text-hover": colorsTuple(themeVars['color-on/alert/default/interactive-text-hover']),
		"color-on-1-scale-default-interactive-text-default": colorsTuple(themeVars['color-on/1-scale/default/interactive-text-default']),
		"color-1-scale-states-selected": colorsTuple(themeVars['color/1-scale/states/selected']),
		"color-warning-states-disabled": colorsTuple(themeVars['color/warning/states/disabled']),
		"color-success-states-focused": colorsTuple(themeVars['color/success/states/focused']),
		"color-alert-states-pressed": colorsTuple(themeVars['color/alert/states/pressed']),
		"color-warning-states-selected": colorsTuple(themeVars['color/warning/states/selected']),
		"color-1-scale-states-pressed": colorsTuple(themeVars['color/1-scale/states/pressed']),
		"color-1-scale-states-focused": colorsTuple(themeVars['color/1-scale/states/focused']),
		"color-success-states-pressed": colorsTuple(themeVars['color/success/states/pressed']),
		"color-success-states-hover": colorsTuple(themeVars['color/success/states/hover']),
		"color-warning-states-hover": colorsTuple(themeVars['color/warning/states/hover']),
		"color-success-states-disabled": colorsTuple(themeVars['color/success/states/disabled']),
		"color-success-states-selected": colorsTuple(themeVars['color/success/states/selected']),
		"color-warning-states-pressed": colorsTuple(themeVars['color/warning/states/pressed']),
		"color-alert-states-disabled": colorsTuple(themeVars['color/alert/states/disabled']),
		"color-alert-states-selected": colorsTuple(themeVars['color/alert/states/selected']),
		"color-1-scale-states-hover": colorsTuple(themeVars['color/1-scale/states/hover']),
		"color-1-scale-states-disabled": colorsTuple(themeVars['color/1-scale/states/disabled']),
		"color-alert-states-focused": colorsTuple(themeVars['color/alert/states/focused']),
		"color-warning-states-focused": colorsTuple(themeVars['color/warning/states/focused']),
		"color-alert-states-hover": colorsTuple(themeVars['color/alert/states/hover']),
		"color-on-warning-default-interactive-text-hover": colorsTuple(themeVars['color-on/warning/default/interactive-text-hover']),
		"color-on-warning-default-interactive-text-default": colorsTuple(themeVars['color-on/warning/default/interactive-text-default']),
		"color-on-warning-default-action-text-disabled 2": colorsTuple(themeVars['color-on/warning/default/action-text-disabled 2']),
		"color-on-warning-default-high-emphasis": colorsTuple(themeVars['color-on/warning/default/high-emphasis']),
		"color-on-warning-default-interactive-text-selected 2": colorsTuple(themeVars['color-on/warning/default/interactive-text-selected 2']),
		"color-on-warning-default-interactive-text-focused": colorsTuple(themeVars['color-on/warning/default/interactive-text-focused']),
		"color-on-warning-default-interactive-text-pressed": colorsTuple(themeVars['color-on/warning/default/interactive-text-pressed']),
		"color-on-warning-default-disabled": colorsTuple(themeVars['color-on/warning/default/disabled']),
		"color-on-warning-default-medium-emphasis": colorsTuple(themeVars['color-on/warning/default/medium-emphasis'])
  },
  radius: {
    "size-border-radius-0-5x": "4px",
		"size-border-radius-4x": "32px",
		"size-border-radius-1-5x": "12px",
		"size-border-radius-3x": "24px",
		"size-border-radius-default": "8px",
		"size-border-radius-2x": "16px"
  },
  fontSizes: {
    "font-size-5xl": "36px",
		"font-size-4xl": "32px",
		"font-size-md": "16px",
		"font-size-6xl": "40px",
		"font-size-3xl": "28px",
		"font-size-2xs": "10px",
		"font-size-2xl": "24px",
		"font-size-xl": "20px",
		"font-size-xs": "12px",
		"font-size-lg": "18px",
		"font-size-sm": "14px"
  }
})