/* prettier-ignore */

/* tslint:disable */
/*
Auto-generated by Recursica.
Do NOT edit these files directly

For more information about Recursica, go to https://recursica.com
*/

export type RecursicaBorderRadiusType = 'size/border-radius/0-5x' | 'size/border-radius/4x' | 'size/border-radius/1-5x' | 'size/border-radius/3x' | 'size/border-radius/default' | 'size/border-radius/2x';
