/* prettier-ignore */
/* eslint-disable */
/* tslint:disable */
/*
Auto-generated by Recursica.
Do NOT edit these files directly

For more information about Recursica, go to https://recursica.com
*/

/// <reference types="vite-plugin-svgr/client" />
import arrow_back_Filled from './Svg/arrow_back_Filled.svg?react';
export { arrow_back_Filled };
import arrow_back_Outlined from './Svg/arrow_back_Outlined.svg?react';
export { arrow_back_Outlined };
import arrow_back_ios_new_Filled from './Svg/arrow_back_ios_new_Filled.svg?react';
export { arrow_back_ios_new_Filled };
import arrow_back_ios_new_Outlined from './Svg/arrow_back_ios_new_Outlined.svg?react';
export { arrow_back_ios_new_Outlined };
import arrow_forward_Filled from './Svg/arrow_forward_Filled.svg?react';
export { arrow_forward_Filled };
import arrow_forward_Outlined from './Svg/arrow_forward_Outlined.svg?react';
export { arrow_forward_Outlined };
import check_Filled from './Svg/check_Filled.svg?react';
export { check_Filled };
import check_Outlined from './Svg/check_Outlined.svg?react';
export { check_Outlined };
import close_Filled from './Svg/close_Filled.svg?react';
export { close_Filled };
import close_Outlined from './Svg/close_Outlined.svg?react';
export { close_Outlined };
import keyboard_arrow_down_Filled from './Svg/keyboard_arrow_down_Filled.svg?react';
export { keyboard_arrow_down_Filled };
import keyboard_arrow_down_Outlined from './Svg/keyboard_arrow_down_Outlined.svg?react';
export { keyboard_arrow_down_Outlined };
import keyboard_arrow_up_Filled from './Svg/keyboard_arrow_up_Filled.svg?react';
export { keyboard_arrow_up_Filled };
import keyboard_arrow_up_Outlined from './Svg/keyboard_arrow_up_Outlined.svg?react';
export { keyboard_arrow_up_Outlined };
import publish_Filled from './Svg/publish_Filled.svg?react';
export { publish_Filled };
import publish_Outlined from './Svg/publish_Outlined.svg?react';
export { publish_Outlined };
import content_copy_Filled from './Svg/content_copy_Filled.svg?react';
export { content_copy_Filled };
import content_copy_Outlined from './Svg/content_copy_Outlined.svg?react';
export { content_copy_Outlined };
import link_Filled from './Svg/link_Filled.svg?react';
export { link_Filled };
import link_Outlined from './Svg/link_Outlined.svg?react';
export { link_Outlined };
import error_Filled from './Svg/error_Filled.svg?react';
export { error_Filled };
import error_Outlined from './Svg/error_Outlined.svg?react';
export { error_Outlined };
import warning_amber_Filled from './Svg/warning_amber_Filled.svg?react';
export { warning_amber_Filled };
import warning_amber_Outlined from './Svg/warning_amber_Outlined.svg?react';
export { warning_amber_Outlined };
import bug_report_Filled from './Svg/bug_report_Filled.svg?react';
export { bug_report_Filled };
import bug_report_Outlined from './Svg/bug_report_Outlined.svg?react';
export { bug_report_Outlined };
import cached_Filled from './Svg/cached_Filled.svg?react';
export { cached_Filled };
import cached_Outlined from './Svg/cached_Outlined.svg?react';
export { cached_Outlined };
import favorite_Filled from './Svg/favorite_Filled.svg?react';
export { favorite_Filled };
import favorite_Outlined from './Svg/favorite_Outlined.svg?react';
export { favorite_Outlined };
import logout_Filled from './Svg/logout_Filled.svg?react';
export { logout_Filled };
import logout_Outlined from './Svg/logout_Outlined.svg?react';
export { logout_Outlined };
import open_in_new_Filled from './Svg/open_in_new_Filled.svg?react';
export { open_in_new_Filled };
import open_in_new_Outlined from './Svg/open_in_new_Outlined.svg?react';
export { open_in_new_Outlined };
import pending_Filled from './Svg/pending_Filled.svg?react';
export { pending_Filled };
import pending_Outlined from './Svg/pending_Outlined.svg?react';
export { pending_Outlined };
