/* prettier-ignore */
/* eslint-disable */
/* tslint:disable */
/*
Auto-generated by Recursica.
Do NOT edit these files directly

For more information about Recursica, go to https://recursica.com
*/

/**
 * Recursica Design System Lookup Object
 * 
 * This object provides type-safe access to all CSS custom properties
 * generated from your design tokens. Use it to style components programmatically.
 * 
 * Example usage:
 * style={{ backgroundColor: recursica.tokens["color/primary/500"] }}
 * style={{ padding: recursica.uiKit["button/size/padding"] }}
 * style={{ color: recursica.themes.light["text/primary"] }}
 */

export const recursica = {
  tokens: {
  "effect/elevation/elevation-0": "var(--effect-elevation-elevation-0)",
  "effect/elevation/elevation-1": "var(--effect-elevation-elevation-1)",
  "effect/elevation/elevation-2": "var(--effect-elevation-elevation-2)",
  "effect/elevation/elevation-3": "var(--effect-elevation-elevation-3)",
  "effect/elevation/elevation-4": "var(--effect-elevation-elevation-4)"
  },
  uiKit: {

  },
  themes: {
  "RecursicaBrand": {

  }
  }
};

export default recursica;
