/* prettier-ignore */
/* eslint-disable */
/* tslint:disable */
/*
Auto-generated by Recursica.
Do NOT edit these files directly

For more information about Recursica, go to https://recursica.com
*/

/**
 * Recursica Design System Type Definitions
 * 
 * Type-safe interfaces for accessing design tokens, UI Kit variables, and themes.
 * These types are automatically generated from your design tokens.
 */

// Token type definitions
export type RecursicaToken = 
  "effect/elevation/elevation-0" |
  "effect/elevation/elevation-1" |
  "effect/elevation/elevation-2" |
  "effect/elevation/elevation-3" |
  "effect/elevation/elevation-4";

// UI Kit type definitions  
export type RecursicaUiKit = 
;

// Theme type definitions
export type RecursicaTheme = 
  "RecursicaBrand";

// Individual theme type definitions
export type RecursicaThemeRecursicaBrand = 
    "Light" |
    "Dark";

// Main recursica object type
export interface Recursica {
  tokens: Record<RecursicaToken, string>;
  uiKit: Record<RecursicaUiKit, string>;
  themes: {
    [K in RecursicaTheme]: K extends keyof RecursicaThemeMap 
      ? RecursicaThemeMap[K] 
      : Record<string, string>;
  };
}

// Theme map for individual theme types
export interface RecursicaThemeMap {
  "RecursicaBrand": Record<RecursicaThemeRecursicaBrand, string>;
}

// CSS Variable type (for direct CSS variable access)
export type RecursicaCSSVariable = `var(--${string})`;
