import { Tokens } from "../shared/tokens";
import type { ExportingResult } from "../types";
import { autoGeneratedFile } from "@recursica/common";

export function generateTokensCss(
  { tokens }: Tokens,
  outputPath: string,
): ExportingResult {
  const tokensCssFilename = "recursica-tokens.css";
  const tokensCssPath = outputPath + "/" + tokensCssFilename;

  // Convert token names to CSS custom property format
  const cssVariables = Object.entries(tokens)
    .filter(
      ([_, value]) => typeof value === "string" || typeof value === "number",
    )
    .map(([key, value]) => {
      // Convert kebab-case to CSS custom property format
      const cssVarName = key.replace(/\//g, "-").toLowerCase();
      return `  --${cssVarName}: ${value};`;
    })
    .join("\n");

  const tokensCssContent = `${autoGeneratedFile()}
/* Recursica Design Tokens */
:root {
${cssVariables}
}
`;

  return {
    content: tokensCssContent,
    path: tokensCssPath,
    filename: tokensCssFilename,
  };
}
