import { Tokens } from "../shared/tokens";
import type { ExportingResult } from "../types";
import { autoGeneratedFile } from "@recursica/common";

export function generateRecursicaObject(
  { tokens, uiKit, themes }: Tokens,
  outputPath: string,
): ExportingResult {
  const recursicaObjectFilename = "recursica.js";
  const recursicaObjectPath = outputPath + "/" + recursicaObjectFilename;

  // Generate tokens object
  const tokensEntries = Object.entries(tokens)
    .filter(
      ([, value]) => typeof value === "string" || typeof value === "number",
    )
    .map(
      ([key]) =>
        `  "${key}": "var(--${key.replace(/[\/\s]/g, "-").toLowerCase()})"`,
    )
    .join(",\n");

  // Generate UI Kit object
  const uiKitEntries = Object.entries(uiKit)
    .map(([key, value]) => {
      const cssVarName = key.replace(/[\/\s]/g, "-").toLowerCase();

      // Handle token references (objects with collection and name)
      if (
        typeof value === "object" &&
        value !== null &&
        "collection" in value &&
        "name" in value
      ) {
        const tokenVarName = (value as { name: string }).name
          .replace(/[\/\s]/g, "-")
          .toLowerCase();
        return `  "${key}": "var(--${tokenVarName})"`;
      }

      // Handle string values that might be token references
      if (typeof value === "string" && value.includes("/")) {
        const tokenVarName = value.replace(/[\/\s]/g, "-").toLowerCase();
        return `  "${key}": "var(--${tokenVarName})"`;
      }

      // Handle direct values
      if (typeof value === "string" || typeof value === "number") {
        return `  "${key}": "var(--${cssVarName})"`;
      }

      return null;
    })
    .filter(Boolean)
    .join(",\n");

  // Generate themes object
  const themesEntries = Object.entries(themes)
    .map(([themeName, themeModes]) => {
      const modeEntries = Object.entries(
        themeModes as Record<string, Record<string, any>>,
      )
        .map(([mode, variables]) => {
          const themeVariables = Object.entries(
            variables as Record<string, any>,
          )
            .map(([key, value]) => {
              const cssVarName = key.replace(/[\/\s]/g, "-").toLowerCase();

              // Handle different value types
              if (typeof value === "string" || typeof value === "number") {
                return `      "${key}": "var(--${cssVarName})"`;
              }

              // Handle object references
              if (
                typeof value === "object" &&
                value !== null &&
                "collection" in value &&
                "name" in value
              ) {
                const ref = value as { collection: string; name: string };
                const refVarName = ref.name
                  .replace(/[\/\s]/g, "-")
                  .toLowerCase();
                return `      "${key}": "var(--${refVarName})"`;
              }

              return null;
            })
            .filter(Boolean)
            .join(",\n");

          return `    "${mode}": {\n${themeVariables}\n    }`;
        })
        .join(",\n");

      return `  "${themeName}": {\n${modeEntries}\n  }`;
    })
    .join(",\n");

  const recursicaObjectContent = `${autoGeneratedFile()}
/**
 * Recursica Design System Lookup Object
 * 
 * This object provides type-safe access to all CSS custom properties
 * generated from your design tokens. Use it to style components programmatically.
 * 
 * Example usage:
 * style={{ backgroundColor: recursica.tokens["color/primary/500"] }}
 * style={{ padding: recursica.uiKit["button/size/padding"] }}
 * style={{ color: recursica.themes.light["text/primary"] }}
 */

export const recursica = {
  tokens: {
${tokensEntries}
  },
  uiKit: {
${uiKitEntries}
  },
  themes: {
${themesEntries}
  }
};

export default recursica;
`;

  return {
    content: recursicaObjectContent,
    path: recursicaObjectPath,
    filename: recursicaObjectFilename,
  };
}
