import { Tokens } from "../shared/tokens";
import type { ExportingResult } from "../types";
import { autoGeneratedFile } from "@recursica/common";
import { TOKEN_CONFIGS, tokensToCssVariables } from "../utils/tokenToCss";

export function generateTokensCss(
  { tokens }: Tokens,
  outputPath: string,
): ExportingResult {
  const tokensCssFilename = "recursica-tokens.css";
  const tokensCssPath = outputPath + "/" + tokensCssFilename;

  // Convert token names to CSS custom property format using abstracted logic
  const cssVariables = tokensToCssVariables(
    tokens,
    TOKEN_CONFIGS.BASIC_TOKENS,
  ).join("\n");

  const tokensCssContent = `${autoGeneratedFile()}
/* Recursica Design Tokens */
:root {
${cssVariables}
}
`;

  return {
    content: tokensCssContent,
    path: tokensCssPath,
    filename: tokensCssFilename,
  };
}
