import { Tokens } from "../shared/tokens";
import type { ExportingResult } from "../types";
import { autoGeneratedFile } from "@recursica/common";
import { TOKEN_CONFIGS, tokensToCssVariables } from "../utils/tokenToCss";

export function generateUiKitCss(
  { uiKit, themes }: Tokens,
  outputPath: string,
): ExportingResult {
  const uiKitCssFilename = "recursica.css";
  const uiKitCssPath = outputPath + "/" + uiKitCssFilename;

  // Generate imports for tokens and all themes

  // Generate UI Kit variables content using abstracted logic
  const cssVariables = tokensToCssVariables(
    uiKit,
    TOKEN_CONFIGS.UI_KIT_TOKENS,
  ).join("\n");

  const uiKitCssContent = `${autoGeneratedFile()}
/* Recursica UI Kit */
@import "./recursica-tokens.css";

:root {
${cssVariables}
}
`;

  return {
    content: uiKitCssContent,
    path: uiKitCssPath,
    filename: uiKitCssFilename,
  };
}
