import { default as academic_cap_outline } from './Svg/academic_cap_outline.svg?react';
import { default as academic_cap_solid } from './Svg/academic_cap_solid.svg?react';
import { default as adjustments_horizontal_outline } from './Svg/adjustments_horizontal_outline.svg?react';
import { default as adjustments_horizontal_solid } from './Svg/adjustments_horizontal_solid.svg?react';
import { default as adjustments_vertical_outline } from './Svg/adjustments_vertical_outline.svg?react';
import { default as adjustments_vertical_solid } from './Svg/adjustments_vertical_solid.svg?react';
import { default as archive_box_outline } from './Svg/archive_box_outline.svg?react';
import { default as archive_box_solid } from './Svg/archive_box_solid.svg?react';
import { default as archive_box_arrow_down_outline } from './Svg/archive_box_arrow_down_outline.svg?react';
import { default as archive_box_arrow_down_solid } from './Svg/archive_box_arrow_down_solid.svg?react';
import { default as arrow_down_outline } from './Svg/arrow_down_outline.svg?react';
import { default as arrow_down_solid } from './Svg/arrow_down_solid.svg?react';
import { default as arrow_down_circle_outline } from './Svg/arrow_down_circle_outline.svg?react';
import { default as arrow_down_circle_solid } from './Svg/arrow_down_circle_solid.svg?react';
import { default as arrow_down_left_outline } from './Svg/arrow_down_left_outline.svg?react';
import { default as arrow_down_left_solid } from './Svg/arrow_down_left_solid.svg?react';
import { default as arrow_down_on_square_outline } from './Svg/arrow_down_on_square_outline.svg?react';
import { default as arrow_down_on_square_solid } from './Svg/arrow_down_on_square_solid.svg?react';
import { default as arrow_down_on_square_stack_outline } from './Svg/arrow_down_on_square_stack_outline.svg?react';
import { default as arrow_down_on_square_stack_solid } from './Svg/arrow_down_on_square_stack_solid.svg?react';
import { default as arrow_down_right_outline } from './Svg/arrow_down_right_outline.svg?react';
import { default as arrow_down_right_solid } from './Svg/arrow_down_right_solid.svg?react';
import { default as arrow_down_tray_outline } from './Svg/arrow_down_tray_outline.svg?react';
import { default as arrow_down_tray_solid } from './Svg/arrow_down_tray_solid.svg?react';
import { default as arrow_left_outline } from './Svg/arrow_left_outline.svg?react';
import { default as arrow_left_solid } from './Svg/arrow_left_solid.svg?react';
import { default as arrow_left_circle_outline } from './Svg/arrow_left_circle_outline.svg?react';
import { default as arrow_left_circle_solid } from './Svg/arrow_left_circle_solid.svg?react';
import { default as arrow_left_end_on_rectangle_outline } from './Svg/arrow_left_end_on_rectangle_outline.svg?react';
import { default as arrow_left_end_on_rectangle_solid } from './Svg/arrow_left_end_on_rectangle_solid.svg?react';
import { default as arrow_left_start_on_rectangle_outline } from './Svg/arrow_left_start_on_rectangle_outline.svg?react';
import { default as arrow_left_start_on_rectangle_solid } from './Svg/arrow_left_start_on_rectangle_solid.svg?react';
import { default as arrow_long_down_outline } from './Svg/arrow_long_down_outline.svg?react';
import { default as arrow_long_down_solid } from './Svg/arrow_long_down_solid.svg?react';
import { default as arrow_long_left_outline } from './Svg/arrow_long_left_outline.svg?react';
import { default as arrow_long_left_solid } from './Svg/arrow_long_left_solid.svg?react';
import { default as arrow_long_right_outline } from './Svg/arrow_long_right_outline.svg?react';
import { default as arrow_long_right_solid } from './Svg/arrow_long_right_solid.svg?react';
import { default as arrow_long_up_outline } from './Svg/arrow_long_up_outline.svg?react';
import { default as arrow_long_up_solid } from './Svg/arrow_long_up_solid.svg?react';
import { default as arrow_path_outline } from './Svg/arrow_path_outline.svg?react';
import { default as arrow_path_solid } from './Svg/arrow_path_solid.svg?react';
import { default as arrow_path_rounded_square_outline } from './Svg/arrow_path_rounded_square_outline.svg?react';
import { default as arrow_path_rounded_square_solid } from './Svg/arrow_path_rounded_square_solid.svg?react';
import { default as arrow_right_outline } from './Svg/arrow_right_outline.svg?react';
import { default as arrow_right_solid } from './Svg/arrow_right_solid.svg?react';
import { default as arrow_right_circle_outline } from './Svg/arrow_right_circle_outline.svg?react';
import { default as arrow_right_circle_solid } from './Svg/arrow_right_circle_solid.svg?react';
import { default as arrow_right_end_on_rectangle_outline } from './Svg/arrow_right_end_on_rectangle_outline.svg?react';
import { default as arrow_right_end_on_rectangle_solid } from './Svg/arrow_right_end_on_rectangle_solid.svg?react';
import { default as arrow_right_start_on_rectangle_outline } from './Svg/arrow_right_start_on_rectangle_outline.svg?react';
import { default as arrow_right_start_on_rectangle_solid } from './Svg/arrow_right_start_on_rectangle_solid.svg?react';
import { default as arrow_top_right_on_square_outline } from './Svg/arrow_top_right_on_square_outline.svg?react';
import { default as arrow_top_right_on_square_solid } from './Svg/arrow_top_right_on_square_solid.svg?react';
import { default as arrow_trending_down_outline } from './Svg/arrow_trending_down_outline.svg?react';
import { default as arrow_trending_down_solid } from './Svg/arrow_trending_down_solid.svg?react';
import { default as arrow_trending_up_outline } from './Svg/arrow_trending_up_outline.svg?react';
import { default as arrow_trending_up_solid } from './Svg/arrow_trending_up_solid.svg?react';
import { default as arrow_turn_down_left_outline } from './Svg/arrow_turn_down_left_outline.svg?react';
import { default as arrow_turn_down_left_solid } from './Svg/arrow_turn_down_left_solid.svg?react';
import { default as arrow_turn_down_right_outline } from './Svg/arrow_turn_down_right_outline.svg?react';
import { default as arrow_turn_down_right_solid } from './Svg/arrow_turn_down_right_solid.svg?react';
import { default as arrow_turn_left_down_outline } from './Svg/arrow_turn_left_down_outline.svg?react';
import { default as arrow_turn_left_down_solid } from './Svg/arrow_turn_left_down_solid.svg?react';
import { default as arrow_turn_left_up_outline } from './Svg/arrow_turn_left_up_outline.svg?react';
import { default as arrow_turn_left_up_solid } from './Svg/arrow_turn_left_up_solid.svg?react';
import { default as arrow_turn_right_down_outline } from './Svg/arrow_turn_right_down_outline.svg?react';
import { default as arrow_turn_right_down_solid } from './Svg/arrow_turn_right_down_solid.svg?react';
import { default as arrow_turn_right_up_solid } from './Svg/arrow_turn_right_up_solid.svg?react';
import { default as arrow_turn_right_up_outline } from './Svg/arrow_turn_right_up_outline.svg?react';
import { default as arrow_turn_up_left_outline } from './Svg/arrow_turn_up_left_outline.svg?react';
import { default as arrow_turn_up_left_solid } from './Svg/arrow_turn_up_left_solid.svg?react';
import { default as arrow_turn_up_right_outline } from './Svg/arrow_turn_up_right_outline.svg?react';
import { default as arrow_turn_up_right_solid } from './Svg/arrow_turn_up_right_solid.svg?react';
import { default as arrow_up_outline } from './Svg/arrow_up_outline.svg?react';
import { default as arrow_up_solid } from './Svg/arrow_up_solid.svg?react';
import { default as arrow_up_circle_outline } from './Svg/arrow_up_circle_outline.svg?react';
import { default as arrow_up_circle_solid } from './Svg/arrow_up_circle_solid.svg?react';
import { default as arrow_up_left_outline } from './Svg/arrow_up_left_outline.svg?react';
import { default as arrow_up_left_solid } from './Svg/arrow_up_left_solid.svg?react';
import { default as arrow_up_on_square_outline } from './Svg/arrow_up_on_square_outline.svg?react';
import { default as arrow_up_on_square_solid } from './Svg/arrow_up_on_square_solid.svg?react';
import { default as arrow_up_on_square_stack_outline } from './Svg/arrow_up_on_square_stack_outline.svg?react';
import { default as arrow_up_on_square_stack_solid } from './Svg/arrow_up_on_square_stack_solid.svg?react';
import { default as arrow_up_right_outline } from './Svg/arrow_up_right_outline.svg?react';
import { default as arrow_up_right_solid } from './Svg/arrow_up_right_solid.svg?react';
import { default as arrow_up_tray_outline } from './Svg/arrow_up_tray_outline.svg?react';
import { default as arrow_up_tray_solid } from './Svg/arrow_up_tray_solid.svg?react';
import { default as arrow_uturn_down_outline } from './Svg/arrow_uturn_down_outline.svg?react';
import { default as arrow_uturn_down_solid } from './Svg/arrow_uturn_down_solid.svg?react';
import { default as arrow_uturn_left_outline } from './Svg/arrow_uturn_left_outline.svg?react';
import { default as arrow_uturn_left_solid } from './Svg/arrow_uturn_left_solid.svg?react';
import { default as arrow_uturn_right_outline } from './Svg/arrow_uturn_right_outline.svg?react';
import { default as arrow_uturn_right_solid } from './Svg/arrow_uturn_right_solid.svg?react';
import { default as arrow_uturn_up_outline } from './Svg/arrow_uturn_up_outline.svg?react';
import { default as arrow_uturn_up_solid } from './Svg/arrow_uturn_up_solid.svg?react';
import { default as arrows_pointing_in_outline } from './Svg/arrows_pointing_in_outline.svg?react';
import { default as arrows_pointing_in_solid } from './Svg/arrows_pointing_in_solid.svg?react';
import { default as arrows_pointing_out_outline } from './Svg/arrows_pointing_out_outline.svg?react';
import { default as arrows_pointing_out_solid } from './Svg/arrows_pointing_out_solid.svg?react';
import { default as arrows_right_left_outline } from './Svg/arrows_right_left_outline.svg?react';
import { default as arrows_right_left_solid } from './Svg/arrows_right_left_solid.svg?react';
import { default as arrows_up_down_outline } from './Svg/arrows_up_down_outline.svg?react';
import { default as arrows_up_down_solid } from './Svg/arrows_up_down_solid.svg?react';
import { default as at_symbol_outline } from './Svg/at_symbol_outline.svg?react';
import { default as at_symbol_solid } from './Svg/at_symbol_solid.svg?react';
import { default as banknotes_outline } from './Svg/banknotes_outline.svg?react';
import { default as banknotes_solid } from './Svg/banknotes_solid.svg?react';
import { default as bars_3_outline } from './Svg/bars_3_outline.svg?react';
import { default as bars_3_solid } from './Svg/bars_3_solid.svg?react';
import { default as bell_outline } from './Svg/bell_outline.svg?react';
import { default as bell_solid } from './Svg/bell_solid.svg?react';
import { default as bell_alert_outline } from './Svg/bell_alert_outline.svg?react';
import { default as bell_alert_solid } from './Svg/bell_alert_solid.svg?react';
import { default as bell_slash_outline } from './Svg/bell_slash_outline.svg?react';
import { default as bell_slash_solid } from './Svg/bell_slash_solid.svg?react';
import { default as bookmark_outline } from './Svg/bookmark_outline.svg?react';
import { default as bookmark_solid } from './Svg/bookmark_solid.svg?react';
import { default as calendar_outline } from './Svg/calendar_outline.svg?react';
import { default as calendar_solid } from './Svg/calendar_solid.svg?react';
import { default as calendar_date_range_outline } from './Svg/calendar_date_range_outline.svg?react';
import { default as calendar_date_range_solid } from './Svg/calendar_date_range_solid.svg?react';
import { default as camera_outline } from './Svg/camera_outline.svg?react';
import { default as camera_solid } from './Svg/camera_solid.svg?react';
import { default as chat_bubble_bottom_center_outline } from './Svg/chat_bubble_bottom_center_outline.svg?react';
import { default as chat_bubble_bottom_center_solid } from './Svg/chat_bubble_bottom_center_solid.svg?react';
import { default as chat_bubble_left_outline } from './Svg/chat_bubble_left_outline.svg?react';
import { default as chat_bubble_left_solid } from './Svg/chat_bubble_left_solid.svg?react';
import { default as chat_bubble_left_ellipsis_outline } from './Svg/chat_bubble_left_ellipsis_outline.svg?react';
import { default as chat_bubble_left_ellipsis_solid } from './Svg/chat_bubble_left_ellipsis_solid.svg?react';
import { default as chat_bubble_left_right_outline } from './Svg/chat_bubble_left_right_outline.svg?react';
import { default as chat_bubble_left_right_solid } from './Svg/chat_bubble_left_right_solid.svg?react';
import { default as chat_bubble_oval_left_outline } from './Svg/chat_bubble_oval_left_outline.svg?react';
import { default as chat_bubble_oval_left_solid } from './Svg/chat_bubble_oval_left_solid.svg?react';
import { default as chat_bubble_oval_left_ellipsis_outline } from './Svg/chat_bubble_oval_left_ellipsis_outline.svg?react';
import { default as chat_bubble_oval_left_ellipsis_solid } from './Svg/chat_bubble_oval_left_ellipsis_solid.svg?react';
import { default as check_outline } from './Svg/check_outline.svg?react';
import { default as check_solid } from './Svg/check_solid.svg?react';
import { default as check_badge_outline } from './Svg/check_badge_outline.svg?react';
import { default as check_badge_solid } from './Svg/check_badge_solid.svg?react';
import { default as check_circle_outline } from './Svg/check_circle_outline.svg?react';
import { default as check_circle_solid } from './Svg/check_circle_solid.svg?react';
import { default as chevron_down_outline } from './Svg/chevron_down_outline.svg?react';
import { default as chevron_down_solid } from './Svg/chevron_down_solid.svg?react';
import { default as chevron_double_left_outline } from './Svg/chevron_double_left_outline.svg?react';
import { default as chevron_double_left_solid } from './Svg/chevron_double_left_solid.svg?react';
import { default as chevron_double_right_outline } from './Svg/chevron_double_right_outline.svg?react';
import { default as chevron_double_right_solid } from './Svg/chevron_double_right_solid.svg?react';
import { default as chevron_left_outline } from './Svg/chevron_left_outline.svg?react';
import { default as chevron_left_solid } from './Svg/chevron_left_solid.svg?react';
import { default as chevron_right_outline } from './Svg/chevron_right_outline.svg?react';
import { default as chevron_right_solid } from './Svg/chevron_right_solid.svg?react';
import { default as chevron_up_outline } from './Svg/chevron_up_outline.svg?react';
import { default as chevron_up_solid } from './Svg/chevron_up_solid.svg?react';
import { default as chevron_up_down_outline } from './Svg/chevron_up_down_outline.svg?react';
import { default as chevron_up_down_solid } from './Svg/chevron_up_down_solid.svg?react';
import { default as clock_outline } from './Svg/clock_outline.svg?react';
import { default as clock_solid } from './Svg/clock_solid.svg?react';
import { default as cog_8_tooth_outline } from './Svg/cog_8_tooth_outline.svg?react';
import { default as cog_8_tooth_solid } from './Svg/cog_8_tooth_solid.svg?react';
import { default as credit_card_outline } from './Svg/credit_card_outline.svg?react';
import { default as credit_card_solid } from './Svg/credit_card_solid.svg?react';
import { default as cube_outline } from './Svg/cube_outline.svg?react';
import { default as cube_solid } from './Svg/cube_solid.svg?react';
import { default as currency_dollar_outline } from './Svg/currency_dollar_outline.svg?react';
import { default as currency_dollar_solid } from './Svg/currency_dollar_solid.svg?react';
import { default as document_outline } from './Svg/document_outline.svg?react';
import { default as document_solid } from './Svg/document_solid.svg?react';
import { default as ellipsis_horizontal_outline } from './Svg/ellipsis_horizontal_outline.svg?react';
import { default as ellipsis_horizontal_solid } from './Svg/ellipsis_horizontal_solid.svg?react';
import { default as envelope_outline } from './Svg/envelope_outline.svg?react';
import { default as envelope_solid } from './Svg/envelope_solid.svg?react';
import { default as exclamation_circle_outline } from './Svg/exclamation_circle_outline.svg?react';
import { default as exclamation_circle_solid } from './Svg/exclamation_circle_solid.svg?react';
import { default as exclamation_triangle_solid } from './Svg/exclamation_triangle_solid.svg?react';
import { default as exclamation_triangle_outline } from './Svg/exclamation_triangle_outline.svg?react';
import { default as face_frown_solid } from './Svg/face_frown_solid.svg?react';
import { default as face_frown_outline } from './Svg/face_frown_outline.svg?react';
import { default as face_smile_solid } from './Svg/face_smile_solid.svg?react';
import { default as face_smile_outline } from './Svg/face_smile_outline.svg?react';
import { default as fire_outline } from './Svg/fire_outline.svg?react';
import { default as fire_solid } from './Svg/fire_solid.svg?react';
import { default as flag_outline } from './Svg/flag_outline.svg?react';
import { default as flag_solid } from './Svg/flag_solid.svg?react';
import { default as folder_outline } from './Svg/folder_outline.svg?react';
import { default as folder_solid } from './Svg/folder_solid.svg?react';
import { default as funnel_outline } from './Svg/funnel_outline.svg?react';
import { default as funnel_solid } from './Svg/funnel_solid.svg?react';
import { default as gift_outline } from './Svg/gift_outline.svg?react';
import { default as gift_solid } from './Svg/gift_solid.svg?react';
import { default as hand_thumb_up_outline } from './Svg/hand_thumb_up_outline.svg?react';
import { default as hand_thumb_up_solid } from './Svg/hand_thumb_up_solid.svg?react';
import { default as hand_thumb_down_outline } from './Svg/hand_thumb_down_outline.svg?react';
import { default as hand_thumb_down_solid } from './Svg/hand_thumb_down_solid.svg?react';
import { default as heart_solid } from './Svg/heart_solid.svg?react';
import { default as heart_outline } from './Svg/heart_outline.svg?react';
import { default as home_outline } from './Svg/home_outline.svg?react';
import { default as home_solid } from './Svg/home_solid.svg?react';
import { default as identification_outline } from './Svg/identification_outline.svg?react';
import { default as identification_solid } from './Svg/identification_solid.svg?react';
import { default as information_circle_outline } from './Svg/information_circle_outline.svg?react';
import { default as information_circle_solid } from './Svg/information_circle_solid.svg?react';
import { default as link_outline } from './Svg/link_outline.svg?react';
import { default as link_solid } from './Svg/link_solid.svg?react';
import { default as lock_closed_outline } from './Svg/lock_closed_outline.svg?react';
import { default as lock_closed_solid } from './Svg/lock_closed_solid.svg?react';
import { default as magnifying_glass_outline } from './Svg/magnifying_glass_outline.svg?react';
import { default as magnifying_glass_solid } from './Svg/magnifying_glass_solid.svg?react';
import { default as megaphone_outline } from './Svg/megaphone_outline.svg?react';
import { default as megaphone_solid } from './Svg/megaphone_solid.svg?react';
import { default as microphone_outline } from './Svg/microphone_outline.svg?react';
import { default as microphone_solid } from './Svg/microphone_solid.svg?react';
import { default as minus_outline } from './Svg/minus_outline.svg?react';
import { default as minus_solid } from './Svg/minus_solid.svg?react';
import { default as paper_airplane_outline } from './Svg/paper_airplane_outline.svg?react';
import { default as paper_airplane_solid } from './Svg/paper_airplane_solid.svg?react';
import { default as paper_clip_outline } from './Svg/paper_clip_outline.svg?react';
import { default as paper_clip_solid } from './Svg/paper_clip_solid.svg?react';
import { default as pencil_outline } from './Svg/pencil_outline.svg?react';
import { default as pencil_solid } from './Svg/pencil_solid.svg?react';
import { default as pencil_square_outline } from './Svg/pencil_square_outline.svg?react';
import { default as pencil_square_solid } from './Svg/pencil_square_solid.svg?react';
import { default as play_outline } from './Svg/play_outline.svg?react';
import { default as play_solid } from './Svg/play_solid.svg?react';
import { default as plus_outline } from './Svg/plus_outline.svg?react';
import { default as plus_solid } from './Svg/plus_solid.svg?react';
import { default as qr_code_outline } from './Svg/qr_code_outline.svg?react';
import { default as qr_code_solid } from './Svg/qr_code_solid.svg?react';
import { default as question_mark_circle_outline } from './Svg/question_mark_circle_outline.svg?react';
import { default as question_mark_circle_solid } from './Svg/question_mark_circle_solid.svg?react';
import { default as receipt_percent_outline } from './Svg/receipt_percent_outline.svg?react';
import { default as receipt_percent_solid } from './Svg/receipt_percent_solid.svg?react';
import { default as share_outline } from './Svg/share_outline.svg?react';
import { default as share_solid } from './Svg/share_solid.svg?react';
import { default as shield_check_outline } from './Svg/shield_check_outline.svg?react';
import { default as shield_check_solid } from './Svg/shield_check_solid.svg?react';
import { default as shopping_bag_outline } from './Svg/shopping_bag_outline.svg?react';
import { default as shopping_bag_solid } from './Svg/shopping_bag_solid.svg?react';
import { default as shopping_cart_outline } from './Svg/shopping_cart_outline.svg?react';
import { default as shopping_cart_solid } from './Svg/shopping_cart_solid.svg?react';
import { default as slash_outline } from './Svg/slash_outline.svg?react';
import { default as slash_solid } from './Svg/slash_solid.svg?react';
import { default as speaker_wave_outline } from './Svg/speaker_wave_outline.svg?react';
import { default as speaker_wave_solid } from './Svg/speaker_wave_solid.svg?react';
import { default as star_outline } from './Svg/star_outline.svg?react';
import { default as star_solid } from './Svg/star_solid.svg?react';
import { default as stop_outline } from './Svg/stop_outline.svg?react';
import { default as stop_solid } from './Svg/stop_solid.svg?react';
import { default as tag_outline } from './Svg/tag_outline.svg?react';
import { default as tag_solid } from './Svg/tag_solid.svg?react';
import { default as trash_outline } from './Svg/trash_outline.svg?react';
import { default as trash_solid } from './Svg/trash_solid.svg?react';
import { default as user_outline } from './Svg/user_outline.svg?react';
import { default as user_solid } from './Svg/user_solid.svg?react';
import { default as user_circle_outline } from './Svg/user_circle_outline.svg?react';
import { default as user_circle_solid } from './Svg/user_circle_solid.svg?react';
import { default as video_camera_outline } from './Svg/video_camera_outline.svg?react';
import { default as video_camera_solid } from './Svg/video_camera_solid.svg?react';
import { default as x_mark_outline } from './Svg/x_mark_outline.svg?react';
import { default as x_mark_solid } from './Svg/x_mark_solid.svg?react';
import { default as github_outline } from './Svg/github_outline.svg?react';
import { default as gitlab_outline } from './Svg/gitlab_outline.svg?react';
export { academic_cap_outline };
export { academic_cap_solid };
export { adjustments_horizontal_outline };
export { adjustments_horizontal_solid };
export { adjustments_vertical_outline };
export { adjustments_vertical_solid };
export { archive_box_outline };
export { archive_box_solid };
export { archive_box_arrow_down_outline };
export { archive_box_arrow_down_solid };
export { arrow_down_outline };
export { arrow_down_solid };
export { arrow_down_circle_outline };
export { arrow_down_circle_solid };
export { arrow_down_left_outline };
export { arrow_down_left_solid };
export { arrow_down_on_square_outline };
export { arrow_down_on_square_solid };
export { arrow_down_on_square_stack_outline };
export { arrow_down_on_square_stack_solid };
export { arrow_down_right_outline };
export { arrow_down_right_solid };
export { arrow_down_tray_outline };
export { arrow_down_tray_solid };
export { arrow_left_outline };
export { arrow_left_solid };
export { arrow_left_circle_outline };
export { arrow_left_circle_solid };
export { arrow_left_end_on_rectangle_outline };
export { arrow_left_end_on_rectangle_solid };
export { arrow_left_start_on_rectangle_outline };
export { arrow_left_start_on_rectangle_solid };
export { arrow_long_down_outline };
export { arrow_long_down_solid };
export { arrow_long_left_outline };
export { arrow_long_left_solid };
export { arrow_long_right_outline };
export { arrow_long_right_solid };
export { arrow_long_up_outline };
export { arrow_long_up_solid };
export { arrow_path_outline };
export { arrow_path_solid };
export { arrow_path_rounded_square_outline };
export { arrow_path_rounded_square_solid };
export { arrow_right_outline };
export { arrow_right_solid };
export { arrow_right_circle_outline };
export { arrow_right_circle_solid };
export { arrow_right_end_on_rectangle_outline };
export { arrow_right_end_on_rectangle_solid };
export { arrow_right_start_on_rectangle_outline };
export { arrow_right_start_on_rectangle_solid };
export { arrow_top_right_on_square_outline };
export { arrow_top_right_on_square_solid };
export { arrow_trending_down_outline };
export { arrow_trending_down_solid };
export { arrow_trending_up_outline };
export { arrow_trending_up_solid };
export { arrow_turn_down_left_outline };
export { arrow_turn_down_left_solid };
export { arrow_turn_down_right_outline };
export { arrow_turn_down_right_solid };
export { arrow_turn_left_down_outline };
export { arrow_turn_left_down_solid };
export { arrow_turn_left_up_outline };
export { arrow_turn_left_up_solid };
export { arrow_turn_right_down_outline };
export { arrow_turn_right_down_solid };
export { arrow_turn_right_up_solid };
export { arrow_turn_right_up_outline };
export { arrow_turn_up_left_outline };
export { arrow_turn_up_left_solid };
export { arrow_turn_up_right_outline };
export { arrow_turn_up_right_solid };
export { arrow_up_outline };
export { arrow_up_solid };
export { arrow_up_circle_outline };
export { arrow_up_circle_solid };
export { arrow_up_left_outline };
export { arrow_up_left_solid };
export { arrow_up_on_square_outline };
export { arrow_up_on_square_solid };
export { arrow_up_on_square_stack_outline };
export { arrow_up_on_square_stack_solid };
export { arrow_up_right_outline };
export { arrow_up_right_solid };
export { arrow_up_tray_outline };
export { arrow_up_tray_solid };
export { arrow_uturn_down_outline };
export { arrow_uturn_down_solid };
export { arrow_uturn_left_outline };
export { arrow_uturn_left_solid };
export { arrow_uturn_right_outline };
export { arrow_uturn_right_solid };
export { arrow_uturn_up_outline };
export { arrow_uturn_up_solid };
export { arrows_pointing_in_outline };
export { arrows_pointing_in_solid };
export { arrows_pointing_out_outline };
export { arrows_pointing_out_solid };
export { arrows_right_left_outline };
export { arrows_right_left_solid };
export { arrows_up_down_outline };
export { arrows_up_down_solid };
export { at_symbol_outline };
export { at_symbol_solid };
export { banknotes_outline };
export { banknotes_solid };
export { bars_3_outline };
export { bars_3_solid };
export { bell_outline };
export { bell_solid };
export { bell_alert_outline };
export { bell_alert_solid };
export { bell_slash_outline };
export { bell_slash_solid };
export { bookmark_outline };
export { bookmark_solid };
export { calendar_outline };
export { calendar_solid };
export { calendar_date_range_outline };
export { calendar_date_range_solid };
export { camera_outline };
export { camera_solid };
export { chat_bubble_bottom_center_outline };
export { chat_bubble_bottom_center_solid };
export { chat_bubble_left_outline };
export { chat_bubble_left_solid };
export { chat_bubble_left_ellipsis_outline };
export { chat_bubble_left_ellipsis_solid };
export { chat_bubble_left_right_outline };
export { chat_bubble_left_right_solid };
export { chat_bubble_oval_left_outline };
export { chat_bubble_oval_left_solid };
export { chat_bubble_oval_left_ellipsis_outline };
export { chat_bubble_oval_left_ellipsis_solid };
export { check_outline };
export { check_solid };
export { check_badge_outline };
export { check_badge_solid };
export { check_circle_outline };
export { check_circle_solid };
export { chevron_down_outline };
export { chevron_down_solid };
export { chevron_double_left_outline };
export { chevron_double_left_solid };
export { chevron_double_right_outline };
export { chevron_double_right_solid };
export { chevron_left_outline };
export { chevron_left_solid };
export { chevron_right_outline };
export { chevron_right_solid };
export { chevron_up_outline };
export { chevron_up_solid };
export { chevron_up_down_outline };
export { chevron_up_down_solid };
export { clock_outline };
export { clock_solid };
export { cog_8_tooth_outline };
export { cog_8_tooth_solid };
export { credit_card_outline };
export { credit_card_solid };
export { cube_outline };
export { cube_solid };
export { currency_dollar_outline };
export { currency_dollar_solid };
export { document_outline };
export { document_solid };
export { ellipsis_horizontal_outline };
export { ellipsis_horizontal_solid };
export { envelope_outline };
export { envelope_solid };
export { exclamation_circle_outline };
export { exclamation_circle_solid };
export { exclamation_triangle_solid };
export { exclamation_triangle_outline };
export { face_frown_solid };
export { face_frown_outline };
export { face_smile_solid };
export { face_smile_outline };
export { fire_outline };
export { fire_solid };
export { flag_outline };
export { flag_solid };
export { folder_outline };
export { folder_solid };
export { funnel_outline };
export { funnel_solid };
export { gift_outline };
export { gift_solid };
export { hand_thumb_up_outline };
export { hand_thumb_up_solid };
export { hand_thumb_down_outline };
export { hand_thumb_down_solid };
export { heart_solid };
export { heart_outline };
export { home_outline };
export { home_solid };
export { identification_outline };
export { identification_solid };
export { information_circle_outline };
export { information_circle_solid };
export { link_outline };
export { link_solid };
export { lock_closed_outline };
export { lock_closed_solid };
export { magnifying_glass_outline };
export { magnifying_glass_solid };
export { megaphone_outline };
export { megaphone_solid };
export { microphone_outline };
export { microphone_solid };
export { minus_outline };
export { minus_solid };
export { paper_airplane_outline };
export { paper_airplane_solid };
export { paper_clip_outline };
export { paper_clip_solid };
export { pencil_outline };
export { pencil_solid };
export { pencil_square_outline };
export { pencil_square_solid };
export { play_outline };
export { play_solid };
export { plus_outline };
export { plus_solid };
export { qr_code_outline };
export { qr_code_solid };
export { question_mark_circle_outline };
export { question_mark_circle_solid };
export { receipt_percent_outline };
export { receipt_percent_solid };
export { share_outline };
export { share_solid };
export { shield_check_outline };
export { shield_check_solid };
export { shopping_bag_outline };
export { shopping_bag_solid };
export { shopping_cart_outline };
export { shopping_cart_solid };
export { slash_outline };
export { slash_solid };
export { speaker_wave_outline };
export { speaker_wave_solid };
export { star_outline };
export { star_solid };
export { stop_outline };
export { stop_solid };
export { tag_outline };
export { tag_solid };
export { trash_outline };
export { trash_solid };
export { user_outline };
export { user_solid };
export { user_circle_outline };
export { user_circle_solid };
export { video_camera_outline };
export { video_camera_solid };
export { x_mark_outline };
export { x_mark_solid };
export { github_outline };
export { gitlab_outline };
