export declare const recursica: {
    "color/salmon/600": string;
    "color/mandy/900": string;
    "color/gray/100": string;
    "color/greensheen/600": string;
    "color/salmon/900": string;
    "font/size/5xl": string;
    "color/mandy/200": string;
    "elevation/blur/5x": string;
    "color/elevation/14": string;
    "color/salmon/300": string;
    "color/salmon/800": string;
    "color/gray/300": string;
    "color/mandarin/300": string;
    "color/elevation/10": string;
    "color/gray/400": string;
    "color/greensheen/200": string;
    "size/gutter/horizontal": string;
    "color/salmon/200": string;
    "color/cornflower/700": string;
    "color/cornflower/800": string;
    "size/spacer/2x": string;
    "color/greensheen/300": string;
    "elevation/y-axis/1-5x": string;
    "color/mandy/500": string;
    "color/gray/600": string;
    "color/greensheen/100": string;
    "color/mandarin/200": string;
    "color/salmon/50": string;
    "size/border-radius/0-5x": string;
    "color/gray/1000": string;
    "color/elevation/12": string;
    "size/border-radius/4x": string;
    "color/greensheen/400": string;
    "size/gutter/vertical": string;
    "color/elevation/25": string;
    "color/gray/050": string;
    "color/cornflower/100": string;
    "color/greensheen/500": string;
    "size/border-radius/1-5x": string;
    "color/greensheen/700": string;
    "size/spacer/1-5x": string;
    "color/gray/200": string;
    "elevation/y-axis/0-5x": string;
    "color/gray/500": string;
    "color/greensheen/50": string;
    "color/cornflower/300": string;
    "color/cornflower/500": string;
    "size/spacer/default": string;
    "color/mandy/700": string;
    "size/spacer/4x": string;
    "color/cornflower/200": string;
    "color/cornflower/600": string;
    "elevation/blur/3x": string;
    "font/size/4xl": string;
    "color/mandy/800": string;
    "size/spacer/0-5x": string;
    "color/cornflower/900": string;
    "size/border-radius/3x": string;
    "color/mandarin/50": string;
    "font/size/md": string;
    "color/mandarin/100": string;
    "size/border-radius/default": string;
    "size/border-radius/2x": string;
    "font/size/6xl": string;
    "color/elevation/40": string;
    "color/elevation/08": string;
    "color/gray/800": string;
    "font/family/lexend": string;
    "color/mandarin/400": string;
    "elevation/blur/1-5x": string;
    "font/size/3xl": string;
    "color/mandy/50": string;
    "color/elevation/20": string;
    "elevation/y-axis/default": string;
    "font/size/2xs": string;
    "color/mandy/400": string;
    "color/mandarin/600": string;
    "color/salmon/500": string;
    "color/greensheen/800": string;
    "elevation/y-axis/3x": string;
    "color/mandy/100": string;
    "elevation/blur/4x": string;
    "color/mandarin/800": string;
    "font/size/2xl": string;
    "color/elevation/18": string;
    "elevation/blur/0-5x": string;
    "color/elevation/35": string;
    "color/gray/700": string;
    "color/mandy/300": string;
    "elevation/blur/6x": string;
    "color/mandarin/700": string;
    "elevation/blur/2x": string;
    "color/salmon/700": string;
    "font/size/xl": string;
    "color/mandarin/500": string;
    "elevation/blur/default": string;
    "color/salmon/100": string;
    "font/size/xs": string;
    "color/mandy/600": string;
    "color/cornflower/400": string;
    "color/cornflower/50": string;
    "size/spacer/3x": string;
    "color/salmon/400": string;
    "elevation/y-axis/4x": string;
    "color/mandarin/900": string;
    "font/size/lg": string;
    "font/size/sm": string;
    "color/greensheen/900": string;
    "elevation/y-axis/2x": string;
    "font/family/quattrocento": string;
    "font/family/bellota": string;
    "color/gray/900": string;
    "opacity/solid": string;
    "opacity/veiled": string;
    "color/gray/000": string;
    "opacity/faint": string;
    "opacity/smoky": string;
    "opacity/ghost": string;
    "elevation/spread/6x": string;
    "elevation/y-axis/5x": string;
    "elevation/spread/2x": string;
    "elevation/x-axis/1-5x": string;
    "elevation/x-axis/default": string;
    "elevation/spread/5x": string;
    "elevation/spread/0-5x": string;
    "elevation/x-axis/0-5x": string;
    "elevation/blur/0": string;
    "elevation/x-axis/2x": string;
    "elevation/x-axis/0": string;
    "elevation/x-axis/3x": string;
    "elevation/y-axis/0": string;
    "elevation/x-axis/5x": string;
    "elevation/spread/3x": string;
    "elevation/spread/0": string;
    "elevation/spread/1-5x": string;
    "elevation/x-axis/4x": string;
    "elevation/spread/4x": string;
    "elevation/y-axis/6x": string;
    "elevation/spread/default": string;
    "elevation/x-axis/6x": string;
    "colors/scale-1/400/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-0/elements/interactive/color": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/050/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/300/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "elevations/elevation-0/blur": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "fonts/subtitle-2/size": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-1/elements/warn-text": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/300/on-tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-1/properties/border-thickness": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-0/elements/success-text": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-3/properties/elevation": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "elevations/elevation-4/spread": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/300/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/100/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "elevations/elevation-1/color": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/400/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "fonts/caption/font-family": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-2/elements/success-text": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/200/tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-1/elements/text/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/200/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "fonts/subtitle-2/font-family": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "fonts/overline/size": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/800/on-tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/400/tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/600/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/200/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/900/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/700/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/800/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "elevations/elevation-2/y-axis": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/500/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "elevations/elevation-4/x-axis": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/400/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-alternatives/high-contrast/elements/text/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-0/elements/interactive/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/600/tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "elevations/elevation-0/x-axis": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-1/properties/elevation": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/300/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/600/tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/300/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/050/on-tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "fonts/h6/font-family": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/500/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/default/tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/300/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-alternatives/success/elements/text/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-3/elements/warn-text": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/500/on-tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/300/on-tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "fonts/h2/size": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "elevations/elevation-1/x-axis": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/700/on-tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/black": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-3/elements/text/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "fonts/h3/font-family": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "fonts/h4/size": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/050/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-3/properties/border-radius": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-2/properties/surface": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "fonts/body-1/font-family": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/800/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-3/elements/text/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-2/elements/text/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/700/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/700/tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-alternatives/success/properties/padding": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/100/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/default/on-tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "fonts/h6/size": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "fonts/button/size": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/600/tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-2/elements/interactive/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "fonts/h3/size": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "elevations/elevation-1/blur": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-alternatives/high-contrast/elements/interactive/color": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "fonts/subtitle-1/size": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/900/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-1/elements/alert-text": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/300/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-alternatives/primary/elements/text/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/800/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/050/tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "fonts/body-2/font-family": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "elevations/elevation-3/y-axis": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-alternatives/success/properties/surface": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "elevations/elevation-4/blur": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/disabled": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-alternatives/high-contrast/elements/text/color": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/100/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/800/on-tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/white": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-alternatives/warn/elements/interactive/color": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/700/on-tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/900/tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-2/elements/interactive/color": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/default/on-tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/200/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/200/on-tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "fonts/overline/font-family": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-alternatives/warn/elements/text/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-1/properties/surface": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/default/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-2/properties/padding": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-1/properties/border-radius": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/800/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "fonts/h1/size": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/400/on-tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-3/properties/padding": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/700/on-tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/050/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/600/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-0/elements/warn-text": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/100/on-tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/600/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/600/on-tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/100/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/200/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-alternatives/primary/properties/padding": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/900/on-tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/100/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-alternatives/primary/properties/surface": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/default/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-2/elements/text/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/100/on-tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-alternatives/warn/elements/interactive/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-0/properties/surface": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/500/on-tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-2/elements/alert-text": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/400/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/400/on-tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "fonts/h1/font-family": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/800/tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/050/tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/200/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/300/tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/050/on-tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "fonts/button/font-family": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/default/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/500/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/100/tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/900/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-alternatives/primary/elements/text/color": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/900/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/700/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/700/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/800/on-tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/800/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/600/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/600/on-tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/800/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-0/elements/text/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-0/properties/padding": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/100/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-alternatives/success/elements/text/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/200/on-tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "elevations/elevation-2/blur": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/800/tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-3/properties/surface": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/500/tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/500/on-tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/500/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "elevations/elevation-2/color": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/default/tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/700/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-2/elements/text/color": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "elevations/elevation-3/color": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-alternatives/warn/elements/text/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "fonts/caption/size": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-alternatives/alert/elements/text/color": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-2/properties/elevation": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/700/tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-0/elements/text/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-1/elements/text/color": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/200/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-1/elements/interactive/color": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/600/on-tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/400/tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/050/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-alternatives/high-contrast/properties/padding": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-alternatives/alert/properties/surface": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "elevations/elevation-3/spread": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-alternatives/warn/properties/padding": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "fonts/body-2/size": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-1/properties/border-color": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-2/properties/border-color": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-2/elements/warn-text": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/300/tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/050/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/900/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/900/on-tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-1/properties/padding": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/900/on-tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/500/tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "fonts/h5/size": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/400/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-3/elements/alert-text": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-alternatives/success/elements/interactive/color": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/default/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "elevations/elevation-0/y-axis": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "fonts/h5/font-family": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-3/elements/success-text": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/900/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-1/elements/text/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/050/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-3/elements/text/color": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/600/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/200/tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "fonts/body-1/size": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "elevations/elevation-3/x-axis": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-3/elements/interactive/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-3/elements/interactive/color": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-alternatives/high-contrast/elements/text/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/050/tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-alternatives/high-contrast/elements/interactive/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "fonts/h2/font-family": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-alternatives/success/elements/interactive/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/default/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-alternatives/primary/elements/interactive/color": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-1/elements/success-text": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "elevations/elevation-0/spread": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-alternatives/alert/elements/interactive/color": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/200/on-tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/500/tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-alternatives/alert/elements/text/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/default/tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-alternatives/alert/elements/text/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-alternatives/alert/elements/interactive/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-1/elements/interactive/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-alternatives/warn/properties/surface": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/default/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-2/properties/border-radius": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/600/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/100/tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/050/on-tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "fonts/subtitle-1/font-family": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "elevations/elevation-3/blur": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-alternatives/warn/elements/text/color": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "elevations/elevation-1/spread": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/overlay": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/800/tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "elevations/elevation-4/y-axis": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/500/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-2/properties/border-thickness": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/100/on-tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/400/tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-3/properties/border-color": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/400/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/900/tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-alternatives/alert/properties/padding": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-2/700/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-0/elements/alert-text": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-alternatives/primary/elements/text/subtle": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-alternatives/success/elements/text/color": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/500/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "elevations/elevation-2/spread": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/300/on-tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/300/tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "elevations/elevation-2/x-axis": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/default/on-tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-alternatives/primary/elements/interactive/regular": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-3/properties/border-thickness": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/900/tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-0/elements/text/color": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/400/on-tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/100/tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "layers/layer-alternatives/high-contrast/properties/surface": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/scale-1/200/tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "fonts/h4/font-family": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/neutral/700/tone": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "elevations/elevation-1/y-axis": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/alert": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/success": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "colors/warning": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    "elevations/elevation-4/color": `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'accordion/color/label': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'accordion/color/chevron': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'accordion/color/border': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'accordion/size/padding': string;
    'accordion/size/spacing': string;
    'accordion/size/min-width': string;
    'accordion/size/max-width': string;
    'accordion/size/height': string;
    'accordion/size/cheveron': string;
    'action-bar/color/background': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'action-bar/size/vertical-padding': string;
    'action-bar/size/horizontal-padding': string;
    'action-bar/size/spacing': string;
    'avatar/color/background-primary': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'avatar/color/border-primary': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'avatar/color/label-primary': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'avatar/color/background-ghost': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'avatar/color/border-ghost': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'avatar/color/label-ghost': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'avatar/color/border-image': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'avatar/size/small': string;
    'avatar/size/default': string;
    'avatar/size/large': string;
    'avatar/size/icon-regular': string;
    'avatar/size/icon-small': string;
    'badge/color/background-default': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'badge/color/background-primary': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'badge/color/background-alert': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'badge/color/background-success': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'badge/color/label-default': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'badge/color/label-primary': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'badge/color/label-alert': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'badge/color/label-success': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'badge/size/padding': string;
    'badge/size/default-min-width': string;
    'badge/size/large-min-width': string;
    'badge/size/default-height': string;
    'badge/size/large-height': string;
    'banner/color/background': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'banner/color/border': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'banner/color/text': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'banner/color/icon-background': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'banner/color/icon-color': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'banner/size/icon-size': string;
    'banner/size/vertical-padding': string;
    'banner/size/horizontal-padding-mobile': string;
    'banner/size/horizontal-padding-tablet-desktop': string;
    'banner/size/horizontal-gap': string;
    'banner/size/vertical-gap': string;
    'breadcrumb/color/interactive': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'breadcrumb/color/no-interactive': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'breadcrumb/size/padding': string;
    'breadcrumb/size/spacing': string;
    'breadcrumb/size/icon-size': string;
    'button/color/background-solid': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'button/color/background-solid-hover': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'button/color/text-solid': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'button/color/border': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'button/color/border-hover': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'button/color/disabled': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'button/size/default-size': string;
    'button/size/default-min-width': string;
    'button/size/default-horizontal-padding': string;
    'button/size/default-icon-padding': string;
    'button/size/default-spacing': string;
    'checkbox/color/checkbox': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'checkbox/color/icon': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'banner/size/mobile-min-width': string;
    'button/size/small-size': string;
    'checkbox/color/disabled': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'chip/color/background-unselected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'checkbox/size/spacing-stacked': string;
    'chip/color/text-unselected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'chip/color/border-unselected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'chip/color/text-selected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'chip/color/border-selected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'chip/color/background-selected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'chip/color/error': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'checkbox/size/spacing-inline': string;
    'chip/size/border-radius': string;
    'date-picker/color/background': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'date-picker/color/border': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'date-picker/color/background-date-selected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'date-picker/color/date-regular': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'date-picker/color/date-selected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'date-picker/color/date-hover': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'date-picker/size/height': string;
    'date-picker/size/width': string;
    'date-picker/size/padding': string;
    'date-picker/size/spacing': string;
    'date-picker/size/row-spacing': string;
    'date-picker/size/button-spacing': string;
    'date-picker/size/border-radius': string;
    'date-picker/size/date-border-radius': string;
    'date-picker/size/date-padding': string;
    'date-picker/size/date-size': string;
    'date-picker/size/month-year-height': string;
    'date-picker/size/month-year-width': string;
    'divider/color/border': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'dropdown/color/background-input': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'dropdown/color/border': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'dropdown/color/border-focus': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'dropdown/color/border-selected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'dropdown/color/border-error': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'dropdown/color/disabled': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'dropdown/size/horizontal-padding': string;
    'dropdown/size/vertical-padding': string;
    'dropdown/size/spacing-stacked': string;
    'dropdown/size/spacing-inline': string;
    'dropdown/size/min-width': string;
    'dropdown/size/max-width': string;
    'dropdown/size/input-height': string;
    'menu/color/surface': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'menu/size/menu-vertical-padding': string;
    'menu/size/menu-horizontal-padding': string;
    'menu/size/border-radius': string;
    'menu/size/min-width': string;
    'menu/size/max-width': string;
    'menu-item/color/default': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'menu-item/color/hover': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'menu-item/color/selected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'menu-item/color/focused': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'menu-item/color/text': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'menu-item/size/item-horizontal-padding': string;
    'menu-item/size/item-vertical-padding': string;
    'menu-item/size/spacing': string;
    'file-upload/color/background': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'file-upload/color/border': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'file-upload/color/icon': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'file-upload/color/text': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'file-upload/size/radius': string;
    'file-upload/size/content-spacing': string;
    'file-upload/size/restrictions-spacing': string;
    'file-upload/size/vertical-padding': string;
    'file-upload/size/horizontal-padding': string;
    'file-upload/size/icon-size': string;
    'form/icon/color/icon-color': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'modal/color/background': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'modal/color/title': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'form/icon/size/icon-size': string;
    'form/label/color/default-color': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'form/label/color/error-message': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'form/label/color/disabled': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'form/label/color/assistive-text': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'form/label/size/label-vertical-padding': string;
    'form/label/size/spacing': string;
    'form/label/size/inline-height': string;
    'form/label/size/inline-width': string;
    'form/value+placeholder/color/input-value': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'form/value+placeholder/size/input-vertical-padding': string;
    'modal/size/button-spacing': string;
    'modal/size/border-radius': string;
    'modal/size/horizontal-padding': string;
    'modal/size/vertical-padding': string;
    'modal/size/min-width': string;
    'modal/size/max-width': string;
    'pagination/color/background-selected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'pagination/size/number-spacing': string;
    'pagination/color/background-hover-selected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'pagination/color/background-hover-unselected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'pagination/color/page-number-default': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'panel/color/background': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'pagination/color/page-number-selected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'pagination/color/page-disabled': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'panel/color/title': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'pagination/color/text': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'panel/size/body-padding': string;
    'radio/color/default': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'radio/color/disabled': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'radio/size/spacing-stacked': string;
    'radio/size/spacing-inline': string;
    'radio/size/spacing-individual': string;
    'radio/size/spacing-group': string;
    'radio/size/border-radius': string;
    'radio/size/border-radius-inside': string;
    'radio/size/dot': string;
    'radio/size/label-vertical-padding': string;
    'radio/size/value-vertical-padding': string;
    'radio/size/width': string;
    'radio/size/height': string;
    'panel/size/header-horizontal-padding': string;
    'panel/size/header-vertical-padding': string;
    'search/color/background': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'panel/size/horizontal-spacing': string;
    'search/color/border': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'search/color/border-focus': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'search/color/border-valued': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'search/size/horizontal-padding': string;
    'search/size/vertical-padding': string;
    'search/size/spacing-inline': string;
    'search/size/radius': string;
    'search/size/min-width': string;
    'search/size/max-width': string;
    'search/size/input-height': string;
    'slider/color/track-unselected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'slider/color/discrete-steps-default': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'slider/color/track-selected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'slider/size/max-width-stacked': string;
    'slider/color/handle': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'slider/color/handle-hovered': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'slider/size/max-width-inline': string;
    'slider/size/max-width-slider': string;
    'slider/size/min-width-slider': string;
    'slider/size/spacing-stacked': string;
    'slider/size/spacing-inline': string;
    'slider/size/spacing-content': string;
    'slider/size/border-radius': string;
    'stepper/color/done-step-background': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'stepper/color/done-step-icon': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'stepper/color/active-step-background': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'stepper/color/active-step-stroke': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'stepper/color/active-step-text': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'stepper/color/next-step-background-enabled': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'stepper/color/next-step-border-enabled': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'stepper/color/next-step-enabled-text': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'stepper/color/step-disabled': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'stepper/size/padding': string;
    'stepper/size/border-radius': string;
    'stepper/size/spacing': string;
    'stepper/size/label-spacing': string;
    'stepper/size/label-horizontal-padding': string;
    'stepper/size/icon-size': string;
    'stepper/size/horizontal-min-width': string;
    'stepper/size/vertical-min-width': string;
    'switch/color/thumb': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'switch/color/track-selected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'switch/color/track-unselected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'switch/color/disabled': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'slider/size/track-height': string;
    'slider/size/vertical-padding-discrete-steps': string;
    'slider/size/handle-size': string;
    'slider/size/discrete-step-size': string;
    'switch/size/spacing-stacked': string;
    'switch/size/spacing-inline': string;
    'chip/size/horizontal-padding': string;
    'chip/size/vertical-padding': string;
    'chip/size/spacing': string;
    'chip/size/icon-size': string;
    'chip/size/max-width': string;
    'checkbox/size/spacing-individual': string;
    'checkbox/size/spacing-group': string;
    'banner/size/mobile-max-width': string;
    'banner/size/desktop-min-width': string;
    'banner/size/desktop-content-max-width': string;
    'checkbox/size/border-radius': string;
    'checkbox/size/checkbox-size': string;
    'button/size/small-min-width': string;
    'switch/size/spacing-standalone': string;
    'switch/size/border-radius-track': string;
    'tab/color/border-unselected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'tab/color/border-selected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'tab/color/label': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'tab/color/label-selected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'tab/color/label-unselected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'tab/size/horizontal-padding': string;
    'tab/size/spacing': string;
    'tab/size/icon-size': string;
    'tab/size/height': string;
    'tab/size/min-width': string;
    'tab/size/label-max-width': string;
    'table/color/cell-background': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'table/color/success': string;
    'table/color/cell-background-hovered': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'table/color/cell-background-selected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'table/color/header-background': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'table/color/header-background-hovered': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'table/color/icon': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'table/color/action-icon': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'table/size/spacing': string;
    'table/size/comfy-height': string;
    'table/size/comfy-vertical-padding': string;
    'table/size/comfy-horizontal-padding': string;
    'table/size/default-height': string;
    'table/size/default-vertical-padding': string;
    'table/size/default-horizontal-padding': string;
    'table/size/small-height': string;
    'table/size/small-vertical-padding': string;
    'table/size/small-horizontal-padding': string;
    'table/size/header-right-horizontal-padding': string;
    'table/size/icon-size': string;
    'table-pagination/color/text': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'table-pagination/color/border': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'table-pagination/color/background': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'table-pagination/size/label-spacing': string;
    'table-pagination/size/horizontal-spacing': string;
    'table-pagination/size/horizontal-padding': string;
    'table-pagination/size/vertical-padding': string;
    'table-pagination/size/min-width': string;
    'button/size/small-horizontal-padding': string;
    'button/size/small-icon-padding': string;
    'button/size/small-spacing': string;
    'button/size/border-radius': string;
    'button/size/border-radius-icon': string;
    'button/size/content-max-width': string;
    'button/size/icon-size': string;
    'text-field/color/border': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'text-field/color/border-focus': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'text-field/color/border-valued': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'text-field/color/border-error': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'text-field/color/background-input': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'text-field/size/horizontal-padding': string;
    'text-field/size/vertical-padding': string;
    'text-field/size/spacing-stacked': string;
    'text-field/size/spacing-inline': string;
    'text-field/size/min-width': string;
    'text-field/size/max-width': string;
    'text-field/size/min-input-height': string;
    'text-field/color/read-only-background': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'time-picker/size/max-width-stacked': string;
    'time-picker/size/stacked-spacing': string;
    'time-picker/size/max-width-inline': string;
    'time-picker/size/inline-spacing': string;
    'time-picker/size/between-spacing': string;
    'time-picker/size/help-text-left-vertical-spacing': string;
    'toast/color/background-default': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'toast/size/vertical-padding': string;
    'toast/size/horizontal-padding': string;
    'toast/size/spacing': string;
    'toast/size/min-width': string;
    'toast/size/max-width': string;
    'toast/size/icon-size': string;
    'toast/color/background-success': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'toast/color/background-error': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'toast/color/text-default': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'toast/color/text-success': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'toast/color/button-on-success': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'toast/color/text-error': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'toast/color/button-on-error': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'tooltip/color/background': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'tooltip/color/text': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'tooltip/size/horizontal-padding': string;
    'tooltip/size/vertical-padding': string;
    'tooltip/size/beak-spacer': string;
    'tooltip/size/radius': string;
    'tooltip/size/max-width': string;
    'text-field/color/disabled': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'slider/color/disabled': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'icon-style': string;
};
