import type { CSSProperties } from "@vanilla-extract/css";
import { recursica } from "../../recursica/Recursica";
export const TypographyVariants = [
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "subtitle-1/normal",
  "subtitle-1/strong",
  "subtitle-2/normal",
  "subtitle-2/strong",
  "body-1/normal",
  "body-1/strong",
  "body-2/normal",
  "body-2/strong",
  "caption",
  "overline",
  "button",
] as const;

export type TypographyVariant = (typeof TypographyVariants)[number];

export const typographies: Record<TypographyVariant, CSSProperties> = {
  h1: {
    fontFamily: recursica["fonts/h1/font-family"],
    fontSize: recursica["fonts/h1/size"],
    fontWeight: 700,
    lineHeight: "auto",
    letterSpacing: 0,
  },
  h2: {
    fontFamily: recursica["fonts/h2/font-family"],
    fontSize: recursica["fonts/h2/size"],
    fontWeight: 600,
    lineHeight: "auto",
    letterSpacing: 0,
  },
  h3: {
    fontFamily: recursica["fonts/h3/font-family"],
    fontSize: recursica["fonts/h3/size"],
    fontWeight: 400,
    lineHeight: "auto",
    letterSpacing: 0,
  },
  h4: {
    fontFamily: recursica["fonts/h4/font-family"],
    fontSize: recursica["fonts/h4/size"],
    fontWeight: 300,
    lineHeight: "auto",
    letterSpacing: 0,
  },
  h5: {
    fontFamily: recursica["fonts/h5/font-family"],
    fontSize: recursica["fonts/h5/size"],
    fontWeight: 500,
    lineHeight: "auto",
    letterSpacing: 0,
  },
  h6: {
    fontFamily: recursica["fonts/h6/font-family"],
    fontSize: recursica["fonts/h6/size"],
    fontWeight: 400,
    lineHeight: "auto",
    letterSpacing: 0,
  },
  "subtitle-1/normal": {
    fontFamily: recursica["fonts/subtitle-1/font-family"],
    fontSize: recursica["fonts/subtitle-1/size"],
    fontWeight: 300,
    lineHeight: 1.3,
    letterSpacing: 0,
  },
  "subtitle-1/strong": {
    fontFamily: recursica["fonts/subtitle-1/font-family"],
    fontSize: recursica["fonts/subtitle-1/size"],
    fontWeight: 700,
    lineHeight: 1.3,
    letterSpacing: 0,
  },
  "subtitle-2/normal": {
    fontFamily: recursica["fonts/subtitle-2/font-family"],
    fontSize: recursica["fonts/subtitle-2/size"],
    fontWeight: 400,
    lineHeight: 1.3,
    letterSpacing: 0,
  },
  "subtitle-2/strong": {
    fontFamily: recursica["fonts/subtitle-2/font-family"],
    fontSize: recursica["fonts/subtitle-2/size"],
    fontWeight: 600,
    lineHeight: 1.3,
    letterSpacing: 0,
  },
  "body-1/normal": {
    fontFamily: recursica["fonts/body-1/font-family"],
    fontSize: recursica["fonts/body-1/size"],
    fontWeight: 400,
    lineHeight: "auto",
    letterSpacing: 0,
  },
  "body-1/strong": {
    fontFamily: recursica["fonts/body-1/font-family"],
    fontSize: recursica["fonts/body-1/size"],
    fontWeight: 600,
    lineHeight: "auto",
    letterSpacing: 0,
  },
  "body-2/normal": {
    fontFamily: recursica["fonts/body-2/font-family"],
    fontSize: recursica["fonts/body-2/size"],
    fontWeight: 400,
    lineHeight: "auto",
    letterSpacing: 0.25,
  },
  "body-2/strong": {
    fontFamily: recursica["fonts/body-2/font-family"],
    fontSize: recursica["fonts/body-2/size"],
    fontWeight: 600,
    lineHeight: "auto",
    letterSpacing: 0.25,
  },
  button: {
    fontFamily: recursica["fonts/button/font-family"],
    fontSize: recursica["fonts/button/size"],
    fontWeight: 400,
    lineHeight: "auto",
    letterSpacing: 0.25,
  },
  caption: {
    fontFamily: recursica["fonts/caption/font-family"],
    fontSize: recursica["fonts/caption/size"],
    fontWeight: 400,
    lineHeight: "auto",
    letterSpacing: 0.25,
  },
  overline: {
    fontFamily: recursica["fonts/overline/font-family"],
    fontSize: recursica["fonts/overline/size"],
    fontWeight: 500,
    lineHeight: "auto",
    letterSpacing: 0.3,
  },
};
