import React from "react";
import {
  RecursicaThemeRecursicaBrand,
  Recursica,
} from "@recursica/official-release/recursica.d";

export type ColorsProps = {
  theme: RecursicaThemeRecursicaBrand;
  recursica: Recursica;
};

export function Colors({ theme, recursica }: ColorsProps) {
  return (
    <div className="section">
      <h2>Colors</h2>
      <table className="color-swatches">
        <thead>
          <tr>
            <th>Black</th>
            <th>White</th>
            <th>Alert</th>
            <th>Warn</th>
            <th>Success</th>
            <th>
              Disabled
              <br />
              (opacity)
            </th>
            <th>
              Overlay
              <br />
              (opacity)
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td
              className="swatch-box"
              style={{
                background:
                  recursica.themes.RecursicaBrand[theme]["palette/black"],
              }}
            />
            <td
              className="swatch-box"
              style={{
                background:
                  recursica.themes.RecursicaBrand[theme]["palette/white"],
              }}
            />
            <td
              className="swatch-box"
              style={{
                background:
                  recursica.themes.RecursicaBrand[theme]["palette/alert"],
              }}
            />
            <td
              className="swatch-box"
              style={{
                background:
                  recursica.themes.RecursicaBrand[theme]["palette/warning"],
              }}
            />
            <td
              className="swatch-box"
              style={{
                background:
                  recursica.themes.RecursicaBrand[theme]["palette/success"],
              }}
            />
            <td
              className="swatch-box"
              style={{
                background:
                  recursica.themes.RecursicaBrand[theme]["palette/black"],
                opacity:
                  recursica.themes.RecursicaBrand[theme]["state/disabled"],
              }}
            />
            <td
              className="swatch-box"
              style={{
                background:
                  recursica.themes.RecursicaBrand[theme]["palette/black"],
                opacity:
                  recursica.themes.RecursicaBrand[theme]["state/overlay"],
              }}
            />
          </tr>
          <tr>
            <td>
              {recursica.themes.RecursicaBrand[theme]["palette/black"]}
              <br />
              palette/black
            </td>
            <td>
              {recursica.themes.RecursicaBrand[theme]["palette/white"]}
              <br />
              palette/white
            </td>
            <td>
              {recursica.themes.RecursicaBrand[theme]["palette/alert"]}
              <br />
              palette/alert
            </td>
            <td>
              {recursica.themes.RecursicaBrand[theme]["palette/warning"]}
              <br />
              palette/warning
            </td>
            <td>
              {recursica.themes.RecursicaBrand[theme]["palette/success"]}
              <br />
              palette/success
            </td>
            <td>
              {recursica.themes.RecursicaBrand[theme]["state/disabled"]}
              <br />
              state/disabled
            </td>
            <td>
              {recursica.themes.RecursicaBrand[theme]["state/overlay"]}
              <br />
              state/overlay
            </td>
          </tr>
        </tbody>
      </table>
      <div className="palette-container">
        <h3>Neutral (Grayscale)</h3>
        <table className="color-palettes">
          <thead>
            <th>Emphasis</th>
            <th>900</th>
            <th>800</th>
            <th>700</th>
            <th>600</th>
            <th>500</th>
            <th>400</th>
            <th>300</th>
            <th className="default">200</th>
            <th>100</th>
            <th>050</th>
          </thead>
          <tbody>
            <tr className="high-emphasis">
              <td>High</td>
              <td
                className="palette-box"
                style={{
                  backgroundColor:
                    recursica.themes.RecursicaBrand[theme][
                      "palette/neutral/900/tone"
                    ],
                }}
              >
                <div
                  className="palette-dot"
                  style={{
                    backgroundColor:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/900/on-tone"
                      ],
                    opacity:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/900/high-emphasis"
                      ],
                  }}
                ></div>
              </td>
              <td
                className="palette-box"
                style={{
                  backgroundColor:
                    recursica.themes.RecursicaBrand[theme][
                      "palette/neutral/800/tone"
                    ],
                }}
              >
                <div
                  className="palette-dot"
                  style={{
                    backgroundColor:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/800/on-tone"
                      ],
                    opacity:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/800/high-emphasis"
                      ],
                  }}
                ></div>
              </td>
              <td
                className="palette-box"
                style={{
                  backgroundColor:
                    recursica.themes.RecursicaBrand[theme][
                      "palette/neutral/700/tone"
                    ],
                }}
              >
                <div
                  className="palette-dot"
                  style={{
                    backgroundColor:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/700/on-tone"
                      ],
                    opacity:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/700/high-emphasis"
                      ],
                  }}
                ></div>
              </td>
              <td
                className="palette-box"
                style={{
                  backgroundColor:
                    recursica.themes.RecursicaBrand[theme][
                      "palette/neutral/600/tone"
                    ],
                }}
              >
                <div
                  className="palette-dot"
                  style={{
                    backgroundColor:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/600/on-tone"
                      ],
                    opacity:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/600/high-emphasis"
                      ],
                  }}
                ></div>
              </td>
              <td
                className="palette-box"
                style={{
                  backgroundColor:
                    recursica.themes.RecursicaBrand[theme][
                      "palette/neutral/500/tone"
                    ],
                }}
              >
                <div
                  className="palette-dot"
                  style={{
                    backgroundColor:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/500/on-tone"
                      ],
                    opacity:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/500/high-emphasis"
                      ],
                  }}
                ></div>
              </td>
              <td
                className="palette-box"
                style={{
                  backgroundColor:
                    recursica.themes.RecursicaBrand[theme][
                      "palette/neutral/400/tone"
                    ],
                }}
              >
                <div
                  className="palette-dot"
                  style={{
                    backgroundColor:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/400/on-tone"
                      ],
                    opacity:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/400/high-emphasis"
                      ],
                  }}
                ></div>
              </td>
              <td
                className="palette-box"
                style={{
                  backgroundColor:
                    recursica.themes.RecursicaBrand[theme][
                      "palette/neutral/300/tone"
                    ],
                }}
              >
                <div
                  className="palette-dot"
                  style={{
                    backgroundColor:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/300/on-tone"
                      ],
                    opacity:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/300/high-emphasis"
                      ],
                  }}
                ></div>
              </td>
              <td
                className="palette-box default"
                style={{
                  backgroundColor:
                    recursica.themes.RecursicaBrand[theme][
                      "palette/neutral/200/tone"
                    ],
                }}
              >
                <div
                  className="palette-dot"
                  style={{
                    backgroundColor:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/200/on-tone"
                      ],
                    opacity:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/200/high-emphasis"
                      ],
                  }}
                ></div>
              </td>
              <td
                className="palette-box"
                style={{
                  backgroundColor:
                    recursica.themes.RecursicaBrand[theme][
                      "palette/neutral/100/tone"
                    ],
                }}
              >
                <div
                  className="palette-dot"
                  style={{
                    backgroundColor:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/100/on-tone"
                      ],
                    opacity:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/100/high-emphasis"
                      ],
                  }}
                ></div>
              </td>
              <td
                className="palette-box"
                style={{
                  backgroundColor:
                    recursica.themes.RecursicaBrand[theme][
                      "palette/neutral/050/tone"
                    ],
                }}
              >
                <div
                  className="palette-dot"
                  style={{
                    backgroundColor:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/050/on-tone"
                      ],
                    opacity:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/050/high-emphasis"
                      ],
                  }}
                ></div>
              </td>
            </tr>
            <tr className="low-emphasis">
              <td>Low</td>
              <td
                className="palette-box"
                style={{
                  backgroundColor:
                    recursica.themes.RecursicaBrand[theme][
                      "palette/neutral/900/tone"
                    ],
                }}
              >
                <div
                  className="palette-dot"
                  style={{
                    backgroundColor:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/900/on-tone"
                      ],
                    opacity:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/900/low-emphasis"
                      ],
                  }}
                ></div>
              </td>
              <td
                className="palette-box"
                style={{
                  backgroundColor:
                    recursica.themes.RecursicaBrand[theme][
                      "palette/neutral/800/tone"
                    ],
                }}
              >
                <div
                  className="palette-dot"
                  style={{
                    backgroundColor:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/800/on-tone"
                      ],
                    opacity:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/800/low-emphasis"
                      ],
                  }}
                ></div>
              </td>
              <td
                className="palette-box"
                style={{
                  backgroundColor:
                    recursica.themes.RecursicaBrand[theme][
                      "palette/neutral/700/tone"
                    ],
                }}
              >
                <div
                  className="palette-dot"
                  style={{
                    backgroundColor:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/700/on-tone"
                      ],
                    opacity:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/700/low-emphasis"
                      ],
                  }}
                ></div>
              </td>
              <td
                className="palette-box"
                style={{
                  backgroundColor:
                    recursica.themes.RecursicaBrand[theme][
                      "palette/neutral/600/tone"
                    ],
                }}
              >
                <div
                  className="palette-dot"
                  style={{
                    backgroundColor:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/600/on-tone"
                      ],
                    opacity:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/600/low-emphasis"
                      ],
                  }}
                ></div>
              </td>
              <td
                className="palette-box"
                style={{
                  backgroundColor:
                    recursica.themes.RecursicaBrand[theme][
                      "palette/neutral/500/tone"
                    ],
                }}
              >
                <div
                  className="palette-dot"
                  style={{
                    backgroundColor:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/500/on-tone"
                      ],
                    opacity:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/500/low-emphasis"
                      ],
                  }}
                ></div>
              </td>
              <td
                className="palette-box"
                style={{
                  backgroundColor:
                    recursica.themes.RecursicaBrand[theme][
                      "palette/neutral/400/tone"
                    ],
                }}
              >
                <div
                  className="palette-dot"
                  style={{
                    backgroundColor:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/400/on-tone"
                      ],
                    opacity:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/400/low-emphasis"
                      ],
                  }}
                ></div>
              </td>
              <td
                className="palette-box"
                style={{
                  backgroundColor:
                    recursica.themes.RecursicaBrand[theme][
                      "palette/neutral/300/tone"
                    ],
                }}
              >
                <div
                  className="palette-dot"
                  style={{
                    backgroundColor:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/300/on-tone"
                      ],
                    opacity:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/300/low-emphasis"
                      ],
                  }}
                ></div>
              </td>
              <td
                className="palette-box default"
                style={{
                  backgroundColor:
                    recursica.themes.RecursicaBrand[theme][
                      "palette/neutral/200/tone"
                    ],
                }}
              >
                <div
                  className="palette-dot"
                  style={{
                    backgroundColor:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/200/on-tone"
                      ],
                    opacity:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/200/low-emphasis"
                      ],
                  }}
                ></div>
              </td>
              <td
                className="palette-box"
                style={{
                  backgroundColor:
                    recursica.themes.RecursicaBrand[theme][
                      "palette/neutral/100/tone"
                    ],
                }}
              >
                <div
                  className="palette-dot"
                  style={{
                    backgroundColor:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/100/on-tone"
                      ],
                    opacity:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/100/low-emphasis"
                      ],
                  }}
                ></div>
              </td>
              <td
                className="palette-box"
                style={{
                  backgroundColor:
                    recursica.themes.RecursicaBrand[theme][
                      "palette/neutral/050/tone"
                    ],
                }}
              >
                <div
                  className="palette-dot"
                  style={{
                    backgroundColor:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/050/on-tone"
                      ],
                    opacity:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/neutral/050/low-emphasis"
                      ],
                  }}
                ></div>
              </td>
            </tr>
            <tr>
              <td>Tone</td>
              <td>
                {
                  recursica.themes.RecursicaBrand[theme][
                    "palette/neutral/900/tone"
                  ]
                }
                <br />
                palette/neutral/900/tone
              </td>
              <td>
                {
                  recursica.themes.RecursicaBrand[theme][
                    "palette/neutral/800/tone"
                  ]
                }
                <br />
                palette/neutral/800/tone
              </td>
              <td>
                {
                  recursica.themes.RecursicaBrand[theme][
                    "palette/neutral/700/tone"
                  ]
                }
                <br />
                palette/neutral/700/tone
              </td>
              <td>
                {
                  recursica.themes.RecursicaBrand[theme][
                    "palette/neutral/600/tone"
                  ]
                }
                <br />
                palette/neutral/600/tone
              </td>
              <td>
                {
                  recursica.themes.RecursicaBrand[theme][
                    "palette/neutral/500/tone"
                  ]
                }
                <br />
                palette/neutral/500/tone
              </td>
              <td>
                {
                  recursica.themes.RecursicaBrand[theme][
                    "palette/neutral/400/tone"
                  ]
                }
                <br />
                palette/neutral/400/tone
              </td>
              <td>
                {
                  recursica.themes.RecursicaBrand[theme][
                    "palette/neutral/300/tone"
                  ]
                }
                <br />
                palette/neutral/300/tone
              </td>
              <td className="default">
                {
                  recursica.themes.RecursicaBrand[theme][
                    "palette/neutral/200/tone"
                  ]
                }
                <br />
                palette/neutral/200/tone
              </td>
              <td>
                {
                  recursica.themes.RecursicaBrand[theme][
                    "palette/neutral/100/tone"
                  ]
                }
                <br />
                palette/neutral/100/tone
              </td>
              <td>
                {
                  recursica.themes.RecursicaBrand[theme][
                    "palette/neutral/050/tone"
                  ]
                }
                <br />
                palette/neutral/050/tone
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  );
}
