import React from "react";
import {
  Recursica,
  RecursicaThemeRecursicaBrand,
} from "@recursica/official-release";

export interface LayersProps {
  theme: RecursicaThemeRecursicaBrand;
  recursica: Recursica;
}
export function Layers({ theme, recursica }: LayersProps) {
  return (
    <div className="section">
      <h2>Layers</h2>

      <div
        className="layer-container"
        style={{
          backgroundColor:
            recursica.themes.RecursicaBrand[theme][
              "layer/layer-0/property/surface"
            ],
          color:
            recursica.themes.RecursicaBrand[theme][
              "layer/layer-0/property/element/text/color"
            ],
          padding:
            recursica.themes.RecursicaBrand[theme][
              "layer/layer-0/property/padding"
            ],
        }}
      >
        <div className="layer-content">
          <div className="layer-text-samples">
            <h3>Layer 0 (Background)</h3>
            <p
              style={{
                opacity:
                  recursica.themes.RecursicaBrand[theme][
                    "layer/layer-0/property/element/text/high-emphasis"
                  ],
              }}
            >
              High Emphasis Text / Icon
            </p>
            <p
              style={{
                opacity:
                  recursica.themes.RecursicaBrand[theme][
                    "layer/layer-0/property/element/text/low-emphasis"
                  ],
              }}
            >
              Low Emphasis Text / Icon
            </p>
            <p
              style={{
                color:
                  recursica.themes.RecursicaBrand[theme][
                    "layer/layer-0/property/element/interactive/color"
                  ],
                opacity:
                  recursica.themes.RecursicaBrand[theme][
                    "layer/layer-0/property/element/interactive/high-emphasis"
                  ],
              }}
            >
              Interactive (Link / Button)
            </p>
            <p
              style={{
                color:
                  recursica.themes.RecursicaBrand[theme][
                    "layer/layer-0/property/element/interactive/color"
                  ],
                opacity:
                  recursica.themes.RecursicaBrand[theme]["palette/disabled"],
              }}
            >
              Disabled Interactive
            </p>
            <p
              style={{
                color:
                  recursica.themes.RecursicaBrand[theme][
                    "layer/layer-0/property/element/text/alert"
                  ],
                opacity:
                  recursica.themes.RecursicaBrand[theme][
                    "layer/layer-0/property/element/interactive/high-emphasis"
                  ],
              }}
            >
              Alert
            </p>
            <p
              style={{
                color:
                  recursica.themes.RecursicaBrand[theme][
                    "layer/layer-0/property/element/text/warning"
                  ],
                opacity:
                  recursica.themes.RecursicaBrand[theme][
                    "layer/layer-0/property/element/interactive/high-emphasis"
                  ],
              }}
            >
              Warning
            </p>
            <p
              style={{
                color:
                  recursica.themes.RecursicaBrand[theme][
                    "layer/layer-0/property/element/text/success"
                  ],
                opacity:
                  recursica.themes.RecursicaBrand[theme][
                    "layer/layer-0/property/element/interactive/high-emphasis"
                  ],
              }}
            >
              Success
            </p>
          </div>

          <div
            className="layer-container"
            style={{
              backgroundColor:
                recursica.themes.RecursicaBrand[theme][
                  "layer/layer-1/property/surface"
                ],
              color:
                recursica.themes.RecursicaBrand[theme][
                  "layer/layer-1/property/element/text/color"
                ],
              padding:
                recursica.themes.RecursicaBrand[theme][
                  "layer/layer-1/property/padding"
                ],
              border: `${recursica.themes.RecursicaBrand[theme]["layer/layer-1/property/border/thickness"]} solid ${recursica.themes.RecursicaBrand[theme]["layer/layer-1/property/border/color"]}`,
              borderRadius:
                recursica.themes.RecursicaBrand[theme][
                  "layer/layer-1/property/border/radius"
                ],
            }}
          >
            <div className="layer-content">
              <div className="layer-text-samples">
                <h3>Layer 1</h3>
                <p
                  style={{
                    opacity:
                      recursica.themes.RecursicaBrand[theme][
                        "layer/layer-1/property/element/text/high-emphasis"
                      ],
                  }}
                >
                  High Emphasis Text / Icon
                </p>
                <p
                  style={{
                    opacity:
                      recursica.themes.RecursicaBrand[theme][
                        "layer/layer-1/property/element/text/low-emphasis"
                      ],
                  }}
                >
                  Low Emphasis Text / Icon
                </p>
                <p
                  style={{
                    color:
                      recursica.themes.RecursicaBrand[theme][
                        "layer/layer-1/property/element/interactive/color"
                      ],
                    opacity:
                      recursica.themes.RecursicaBrand[theme][
                        "layer/layer-1/property/element/interactive/high-emphasis"
                      ],
                  }}
                >
                  Interactive (Link / Button)
                </p>
                <p
                  style={{
                    color:
                      recursica.themes.RecursicaBrand[theme][
                        "layer/layer-1/property/element/interactive/color"
                      ],
                    opacity:
                      recursica.themes.RecursicaBrand[theme][
                        "palette/disabled"
                      ],
                  }}
                >
                  Disabled Interactive
                </p>
                <p
                  style={{
                    color:
                      recursica.themes.RecursicaBrand[theme][
                        "layer/layer-1/property/element/text/alert"
                      ],
                    opacity:
                      recursica.themes.RecursicaBrand[theme][
                        "layer/layer-1/property/element/interactive/high-emphasis"
                      ],
                  }}
                >
                  Alert
                </p>
                <p
                  style={{
                    color:
                      recursica.themes.RecursicaBrand[theme][
                        "layer/layer-1/property/element/text/warning"
                      ],
                    opacity:
                      recursica.themes.RecursicaBrand[theme][
                        "layer/layer-1/property/element/interactive/high-emphasis"
                      ],
                  }}
                >
                  Warning
                </p>
                <p
                  style={{
                    color:
                      recursica.themes.RecursicaBrand[theme][
                        "layer/layer-1/property/element/text/success"
                      ],
                    opacity:
                      recursica.themes.RecursicaBrand[theme][
                        "layer/layer-1/property/element/interactive/high-emphasis"
                      ],
                  }}
                >
                  Success
                </p>
              </div>

              <div
                className="layer-container"
                style={{
                  backgroundColor:
                    recursica.themes.RecursicaBrand[theme][
                      "layer/layer-2/property/surface"
                    ],
                  color:
                    recursica.themes.RecursicaBrand[theme][
                      "layer/layer-2/property/element/text/color"
                    ],
                  padding:
                    recursica.themes.RecursicaBrand[theme][
                      "layer/layer-2/property/padding"
                    ],
                  border: `${recursica.themes.RecursicaBrand[theme]["layer/layer-2/property/border/thickness"]} solid ${recursica.themes.RecursicaBrand[theme]["layer/layer-2/property/border/color"]}`,
                  borderRadius:
                    recursica.themes.RecursicaBrand[theme][
                      "layer/layer-2/property/border/radius"
                    ],
                }}
              >
                <div className="layer-content">
                  <div className="layer-text-samples">
                    <h3>Layer 2</h3>
                    <p
                      style={{
                        opacity:
                          recursica.themes.RecursicaBrand[theme][
                            "layer/layer-2/property/element/text/high-emphasis"
                          ],
                      }}
                    >
                      High Emphasis Text / Icon
                    </p>
                    <p
                      style={{
                        opacity:
                          recursica.themes.RecursicaBrand[theme][
                            "layer/layer-2/property/element/text/low-emphasis"
                          ],
                      }}
                    >
                      Low Emphasis Text / Icon
                    </p>
                    <p
                      style={{
                        color:
                          recursica.themes.RecursicaBrand[theme][
                            "layer/layer-2/property/element/interactive/color"
                          ],
                        opacity:
                          recursica.themes.RecursicaBrand[theme][
                            "layer/layer-2/property/element/interactive/high-emphasis"
                          ],
                      }}
                    >
                      Interactive (Link / Button)
                    </p>
                    <p
                      style={{
                        color:
                          recursica.themes.RecursicaBrand[theme][
                            "layer/layer-2/property/element/interactive/color"
                          ],
                        opacity:
                          recursica.themes.RecursicaBrand[theme][
                            "palette/disabled"
                          ],
                      }}
                    >
                      Disabled Interactive
                    </p>
                    <p
                      style={{
                        color:
                          recursica.themes.RecursicaBrand[theme][
                            "layer/layer-2/property/element/text/alert"
                          ],
                        opacity:
                          recursica.themes.RecursicaBrand[theme][
                            "layer/layer-2/property/element/interactive/high-emphasis"
                          ],
                      }}
                    >
                      Alert
                    </p>
                    <p
                      style={{
                        color:
                          recursica.themes.RecursicaBrand[theme][
                            "layer/layer-2/property/element/text/warning"
                          ],
                        opacity:
                          recursica.themes.RecursicaBrand[theme][
                            "layer/layer-2/property/element/interactive/high-emphasis"
                          ],
                      }}
                    >
                      Warning
                    </p>
                    <p
                      style={{
                        color:
                          recursica.themes.RecursicaBrand[theme][
                            "layer/layer-2/property/element/text/success"
                          ],
                        opacity:
                          recursica.themes.RecursicaBrand[theme][
                            "layer/layer-2/property/element/interactive/high-emphasis"
                          ],
                      }}
                    >
                      Success
                    </p>
                  </div>

                  <div
                    className="layer-container"
                    style={{
                      backgroundColor:
                        recursica.themes.RecursicaBrand[theme][
                          "layer/layer-3/property/surface"
                        ],
                      color:
                        recursica.themes.RecursicaBrand[theme][
                          "layer/layer-3/property/element/text/color"
                        ],
                      padding:
                        recursica.themes.RecursicaBrand[theme][
                          "layer/layer-3/property/padding"
                        ],
                      border: `${recursica.themes.RecursicaBrand[theme]["layer/layer-3/property/border/thickness"]} solid ${recursica.themes.RecursicaBrand[theme]["layer/layer-3/property/border/color"]}`,
                      borderRadius:
                        recursica.themes.RecursicaBrand[theme][
                          "layer/layer-3/property/border/radius"
                        ],
                    }}
                  >
                    <div className="layer-content">
                      <div className="layer-text-samples">
                        <h3>Layer 3</h3>
                        <p
                          style={{
                            opacity:
                              recursica.themes.RecursicaBrand[theme][
                                "layer/layer-3/property/element/text/high-emphasis"
                              ],
                          }}
                        >
                          High Emphasis Text / Icon
                        </p>
                        <p
                          style={{
                            opacity:
                              recursica.themes.RecursicaBrand[theme][
                                "layer/layer-3/property/element/text/low-emphasis"
                              ],
                          }}
                        >
                          Low Emphasis Text / Icon
                        </p>
                        <p
                          style={{
                            color:
                              recursica.themes.RecursicaBrand[theme][
                                "layer/layer-3/property/element/interactive/color"
                              ],
                            opacity:
                              recursica.themes.RecursicaBrand[theme][
                                "layer/layer-3/property/element/interactive/high-emphasis"
                              ],
                          }}
                        >
                          Interactive (Link / Button)
                        </p>
                        <p
                          style={{
                            color:
                              recursica.themes.RecursicaBrand[theme][
                                "layer/layer-3/property/element/interactive/color"
                              ],
                            opacity:
                              recursica.themes.RecursicaBrand[theme][
                                "palette/disabled"
                              ],
                          }}
                        >
                          Disabled Interactive
                        </p>
                        <p
                          style={{
                            color:
                              recursica.themes.RecursicaBrand[theme][
                                "layer/layer-3/property/element/text/alert"
                              ],
                            opacity:
                              recursica.themes.RecursicaBrand[theme][
                                "layer/layer-3/property/element/interactive/high-emphasis"
                              ],
                          }}
                        >
                          Alert
                        </p>
                        <p
                          style={{
                            color:
                              recursica.themes.RecursicaBrand[theme][
                                "layer/layer-3/property/element/text/warning"
                              ],
                            opacity:
                              recursica.themes.RecursicaBrand[theme][
                                "layer/layer-3/property/element/interactive/high-emphasis"
                              ],
                          }}
                        >
                          Warning
                        </p>
                        <p
                          style={{
                            color:
                              recursica.themes.RecursicaBrand[theme][
                                "layer/layer-3/property/element/text/success"
                              ],
                            opacity:
                              recursica.themes.RecursicaBrand[theme][
                                "layer/layer-3/property/element/interactive/high-emphasis"
                              ],
                          }}
                        >
                          Success
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
