export declare const uiKit: {
    'accordion/color/label': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'accordion/color/chevron': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'accordion/color/border': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'accordion/size/padding': string;
    'accordion/size/spacing': string;
    'accordion/size/min-width': string;
    'accordion/size/max-width': string;
    'accordion/size/height': string;
    'accordion/size/cheveron': string;
    'action-bar/color/background': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'action-bar/size/vertical-padding': string;
    'action-bar/size/horizontal-padding': string;
    'action-bar/size/spacing': string;
    'avatar/color/background-primary': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'avatar/color/border-primary': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'avatar/color/label-primary': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'avatar/color/background-ghost': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'avatar/color/border-ghost': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'avatar/color/label-ghost': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'avatar/color/border-image': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'avatar/size/small': string;
    'avatar/size/default': string;
    'avatar/size/large': string;
    'avatar/size/icon-regular': string;
    'avatar/size/icon-small': string;
    'badge/color/background-default': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'badge/color/background-primary': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'badge/color/background-alert': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'badge/color/background-success': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'badge/color/label-default': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'badge/color/label-primary': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'badge/color/label-alert': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'badge/color/label-success': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'badge/size/padding': string;
    'badge/size/default-min-width': string;
    'badge/size/large-min-width': string;
    'badge/size/default-height': string;
    'badge/size/large-height': string;
    'banner/color/background': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'banner/color/border': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'banner/color/text': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'banner/color/icon-background': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'banner/color/icon-color': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'banner/size/icon-size': string;
    'banner/size/vertical-padding': string;
    'banner/size/horizontal-padding-mobile': string;
    'banner/size/horizontal-padding-tablet-desktop': string;
    'banner/size/horizontal-gap': string;
    'banner/size/vertical-gap': string;
    'breadcrumb/color/interactive': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'breadcrumb/color/no-interactive': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'breadcrumb/size/padding': string;
    'breadcrumb/size/spacing': string;
    'breadcrumb/size/icon-size': string;
    'button/color/background-solid': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'button/color/background-solid-hover': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'button/color/text-solid': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'button/color/border': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'button/color/border-hover': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'button/color/disabled': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'button/size/default-size': string;
    'button/size/default-min-width': string;
    'button/size/default-horizontal-padding': string;
    'button/size/default-icon-padding': string;
    'button/size/default-spacing': string;
    'checkbox/color/checkbox': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'checkbox/color/icon': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'banner/size/mobile-min-width': string;
    'button/size/small-size': string;
    'checkbox/color/disabled': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'chip/color/background-unselected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'checkbox/size/spacing-stacked': string;
    'chip/color/text-unselected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'chip/color/border-unselected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'chip/color/text-selected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'chip/color/border-selected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'chip/color/background-selected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'chip/color/error': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'checkbox/size/spacing-inline': string;
    'chip/size/border-radius': string;
    'date-picker/color/background': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'date-picker/color/border': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'date-picker/color/background-date-selected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'date-picker/color/date-regular': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'date-picker/color/date-selected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'date-picker/color/date-hover': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'date-picker/size/height': string;
    'date-picker/size/width': string;
    'date-picker/size/padding': string;
    'date-picker/size/spacing': string;
    'date-picker/size/row-spacing': string;
    'date-picker/size/button-spacing': string;
    'date-picker/size/border-radius': string;
    'date-picker/size/date-border-radius': string;
    'date-picker/size/date-padding': string;
    'date-picker/size/date-size': string;
    'date-picker/size/month-year-height': string;
    'date-picker/size/month-year-width': string;
    'divider/color/border': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'dropdown/color/background-input': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'dropdown/color/border': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'dropdown/color/border-focus': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'dropdown/color/border-selected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'dropdown/color/border-error': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'dropdown/color/disabled': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'dropdown/size/horizontal-padding': string;
    'dropdown/size/vertical-padding': string;
    'dropdown/size/spacing-stacked': string;
    'dropdown/size/spacing-inline': string;
    'dropdown/size/min-width': string;
    'dropdown/size/max-width': string;
    'dropdown/size/input-height': string;
    'menu/color/surface': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'menu/size/menu-vertical-padding': string;
    'menu/size/menu-horizontal-padding': string;
    'menu/size/border-radius': string;
    'menu/size/min-width': string;
    'menu/size/max-width': string;
    'menu-item/color/default': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'menu-item/color/hover': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'menu-item/color/selected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'menu-item/color/focused': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'menu-item/color/text': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'menu-item/size/item-horizontal-padding': string;
    'menu-item/size/item-vertical-padding': string;
    'menu-item/size/spacing': string;
    'file-upload/color/background': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'file-upload/color/border': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'file-upload/color/icon': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'file-upload/color/text': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'file-upload/size/radius': string;
    'file-upload/size/content-spacing': string;
    'file-upload/size/restrictions-spacing': string;
    'file-upload/size/vertical-padding': string;
    'file-upload/size/horizontal-padding': string;
    'file-upload/size/icon-size': string;
    'form/icon/color/icon-color': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'modal/color/background': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'modal/color/title': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'form/icon/size/icon-size': string;
    'form/label/color/default-color': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'form/label/color/error-message': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'form/label/color/disabled': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'form/label/color/assistive-text': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'form/label/size/label-vertical-padding': string;
    'form/label/size/spacing': string;
    'form/label/size/inline-height': string;
    'form/label/size/inline-width': string;
    'form/value+placeholder/color/input-value': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'form/value+placeholder/size/input-vertical-padding': string;
    'modal/size/button-spacing': string;
    'modal/size/border-radius': string;
    'modal/size/horizontal-padding': string;
    'modal/size/vertical-padding': string;
    'modal/size/min-width': string;
    'modal/size/max-width': string;
    'pagination/color/background-selected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'pagination/size/number-spacing': string;
    'pagination/color/background-hover-selected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'pagination/color/background-hover-unselected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'pagination/color/page-number-default': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'panel/color/background': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'pagination/color/page-number-selected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'pagination/color/page-disabled': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'panel/color/title': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'pagination/color/text': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'panel/size/body-padding': string;
    'radio/color/default': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'radio/color/disabled': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'radio/size/spacing-stacked': string;
    'radio/size/spacing-inline': string;
    'radio/size/spacing-individual': string;
    'radio/size/spacing-group': string;
    'radio/size/border-radius': string;
    'radio/size/border-radius-inside': string;
    'radio/size/dot': string;
    'radio/size/label-vertical-padding': string;
    'radio/size/value-vertical-padding': string;
    'radio/size/width': string;
    'radio/size/height': string;
    'panel/size/header-horizontal-padding': string;
    'panel/size/header-vertical-padding': string;
    'search/color/background': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'panel/size/horizontal-spacing': string;
    'search/color/border': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'search/color/border-focus': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'search/color/border-valued': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'search/size/horizontal-padding': string;
    'search/size/vertical-padding': string;
    'search/size/spacing-inline': string;
    'search/size/radius': string;
    'search/size/min-width': string;
    'search/size/max-width': string;
    'search/size/input-height': string;
    'slider/color/track-unselected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'slider/color/discrete-steps-default': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'slider/color/track-selected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'slider/size/max-width-stacked': string;
    'slider/color/handle': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'slider/color/handle-hovered': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'slider/size/max-width-inline': string;
    'slider/size/max-width-slider': string;
    'slider/size/min-width-slider': string;
    'slider/size/spacing-stacked': string;
    'slider/size/spacing-inline': string;
    'slider/size/spacing-content': string;
    'slider/size/border-radius': string;
    'stepper/color/done-step-background': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'stepper/color/done-step-icon': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'stepper/color/active-step-background': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'stepper/color/active-step-stroke': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'stepper/color/active-step-text': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'stepper/color/next-step-background-enabled': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'stepper/color/next-step-border-enabled': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'stepper/color/next-step-enabled-text': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'stepper/color/step-disabled': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'stepper/size/padding': string;
    'stepper/size/border-radius': string;
    'stepper/size/spacing': string;
    'stepper/size/label-spacing': string;
    'stepper/size/label-horizontal-padding': string;
    'stepper/size/icon-size': string;
    'stepper/size/horizontal-min-width': string;
    'stepper/size/vertical-min-width': string;
    'switch/color/thumb': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'switch/color/track-selected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'switch/color/track-unselected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'switch/color/disabled': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'slider/size/track-height': string;
    'slider/size/vertical-padding-discrete-steps': string;
    'slider/size/handle-size': string;
    'slider/size/discrete-step-size': string;
    'switch/size/spacing-stacked': string;
    'switch/size/spacing-inline': string;
    'chip/size/horizontal-padding': string;
    'chip/size/vertical-padding': string;
    'chip/size/spacing': string;
    'chip/size/icon-size': string;
    'chip/size/max-width': string;
    'checkbox/size/spacing-individual': string;
    'checkbox/size/spacing-group': string;
    'banner/size/mobile-max-width': string;
    'banner/size/desktop-min-width': string;
    'banner/size/desktop-content-max-width': string;
    'checkbox/size/border-radius': string;
    'checkbox/size/checkbox-size': string;
    'button/size/small-min-width': string;
    'switch/size/spacing-standalone': string;
    'switch/size/border-radius-track': string;
    'tab/color/border-unselected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'tab/color/border-selected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'tab/color/label': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'tab/color/label-selected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'tab/color/label-unselected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'tab/size/horizontal-padding': string;
    'tab/size/spacing': string;
    'tab/size/icon-size': string;
    'tab/size/height': string;
    'tab/size/min-width': string;
    'tab/size/label-max-width': string;
    'table/color/cell-background': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'table/color/success': string;
    'table/color/cell-background-hovered': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'table/color/cell-background-selected': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'table/color/header-background': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'table/color/header-background-hovered': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'table/color/icon': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'table/color/action-icon': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'table/size/spacing': string;
    'table/size/comfy-height': string;
    'table/size/comfy-vertical-padding': string;
    'table/size/comfy-horizontal-padding': string;
    'table/size/default-height': string;
    'table/size/default-vertical-padding': string;
    'table/size/default-horizontal-padding': string;
    'table/size/small-height': string;
    'table/size/small-vertical-padding': string;
    'table/size/small-horizontal-padding': string;
    'table/size/header-right-horizontal-padding': string;
    'table/size/icon-size': string;
    'table-pagination/color/text': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'table-pagination/color/border': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'table-pagination/color/background': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'table-pagination/size/label-spacing': string;
    'table-pagination/size/horizontal-spacing': string;
    'table-pagination/size/horizontal-padding': string;
    'table-pagination/size/vertical-padding': string;
    'table-pagination/size/min-width': string;
    'button/size/small-horizontal-padding': string;
    'button/size/small-icon-padding': string;
    'button/size/small-spacing': string;
    'button/size/border-radius': string;
    'button/size/border-radius-icon': string;
    'button/size/content-max-width': string;
    'button/size/icon-size': string;
    'text-field/color/border': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'text-field/color/border-focus': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'text-field/color/border-valued': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'text-field/color/border-error': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'text-field/color/background-input': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'text-field/size/horizontal-padding': string;
    'text-field/size/vertical-padding': string;
    'text-field/size/spacing-stacked': string;
    'text-field/size/spacing-inline': string;
    'text-field/size/min-width': string;
    'text-field/size/max-width': string;
    'text-field/size/min-input-height': string;
    'text-field/color/read-only-background': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'time-picker/size/max-width-stacked': string;
    'time-picker/size/stacked-spacing': string;
    'time-picker/size/max-width-inline': string;
    'time-picker/size/inline-spacing': string;
    'time-picker/size/between-spacing': string;
    'time-picker/size/help-text-left-vertical-spacing': string;
    'toast/color/background-default': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'toast/size/vertical-padding': string;
    'toast/size/horizontal-padding': string;
    'toast/size/spacing': string;
    'toast/size/min-width': string;
    'toast/size/max-width': string;
    'toast/size/icon-size': string;
    'toast/color/background-success': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'toast/color/background-error': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'toast/color/text-default': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'toast/color/text-success': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'toast/color/button-on-success': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'toast/color/text-error': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'toast/color/button-on-error': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'tooltip/color/background': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'tooltip/color/text': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'tooltip/size/horizontal-padding': string;
    'tooltip/size/vertical-padding': string;
    'tooltip/size/beak-spacer': string;
    'tooltip/size/radius': string;
    'tooltip/size/max-width': string;
    'text-field/color/disabled': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'slider/color/disabled': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
    'icon-style': string;
};
