/* prettier-ignore */
/* eslint-disable */
/* tslint:disable */
/*
Auto-generated by Recursica.
Do NOT edit these files directly

For more information about Recursica, go to https://recursica.com
*/

import { THEMES } from "./RecursicaThemes";

export interface ThemeVariant {
  Dark: string;
  Light: string;
}

// TypeScript will automatically infer this as a union of literal types
export type ThemeType = (typeof THEMES)[keyof typeof THEMES];

export type ThemeDictionary = Record<ThemeType, ThemeVariant>;
