# This workflow runs checks on pull requests to ensure code quality and prevent regressions.
name: Pull Request Check

on:
  # This action triggers on pull requests targeting the main branch.
  pull_request:
    branches: [main]

jobs:
  check-pull-request:
    # Don't run on changeset-release branches
    if: ${{ !startsWith(github.head_ref, 'changeset-release') }}
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Checkout
        uses: actions/checkout@v4

      # Sets up a specific version of Node.js.
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      # Installs project dependencies using a clean install from package-lock.json.
      - name: Install dependencies
        run: npm ci
        env:
          # This prevents husky from installing git hooks during the CI process
          HUSKY: 0

      - name: Cache turbo files
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.ref_name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-turbo-${{ github.ref_name }}-
            ${{ runner.os }}-turbo-

      # Runs TypeScript type checking.
      - name: Check types
        run: npm run check-types

      # Builds the project.
      - name: Build
        run: npm run build
        env:
          # Production environment variables (for main plugin)
          VITE_RECURSICA_API_URL: ${{ vars.RECURSICA_API }}
          VITE_RECURSICA_UI_URL: ${{ vars.RECURSICA_API }}
          VITE_PLUGIN_PHRASE: ${{ secrets.PLUGIN_PHRASE }}
          # Test environment variables (for test plugin)
          VITE_RECURSICA_API_TEST: ${{ vars.RECURSICA_API_TEST }}
          VITE_PLUGIN_PHRASE_TEST: ${{ secrets.PLUGIN_PHRASE_TEST }}

      # Runs the test suite.
      - name: Test
        run: npm run test
