# This workflow automates the versioning and release process using Changesets.
#
# How it works:
# 1. When you push `.changeset` files to the `main` branch, this workflow
#    opens a "Version Packages" pull request. This PR contains updated package
#    versions and changelogs.
# 2. When the "Version Packages" PR is merged, the workflow triggers again. This
#    time, it builds the packages, publishes them to npm, and creates a
#    corresponding GitHub Release.
#
# Caching for npm dependencies and Turborepo build artifacts is enabled to
# optimize workflow speed.
name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # To create releases and tags
      pull-requests: write # To create pull requests
    steps:
      # Checks-out the repository. `fetch-depth: 0` is required for Changesets to correctly
      # determine the changes and version bumps.
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Sets up Node.js and caches the npm dependency directory. This speeds up
      # subsequent `npm ci` runs. It also creates an .npmrc file for publishing.
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      # Installs dependencies using a clean install.
      # HUSKY: 0 prevents Husky git hooks from running during the CI process.
      - name: Install dependencies
        run: npm ci
        env:
          # This prevents husky from installing git hooks during the CI process
          HUSKY: 0

      # Check if there are changes for the figma-plugin
      # Check for actual version changes (more robust)
      - name: Check for figma-plugin version changes
        id: check-figma-plugin
        run: |
          # Get current version
          current_version=$(jq -r '.version' apps/figma-plugin/package.json 2>/dev/null || echo "")

          # Get previous version
          previous_version=$(git show HEAD~1:apps/figma-plugin/package.json 2>/dev/null | jq -r '.version' 2>/dev/null || echo "")

          if [ -n "$current_version" ] && [ -n "$previous_version" ] && [ "$current_version" != "$previous_version" ]; then
            echo "has-figma-changes=true" >> $GITHUB_OUTPUT
            echo "✅ Figma plugin version changed: $previous_version → $current_version"
            echo "🚀 Preparing for PRODUCTION deployment"
          else
            echo "has-figma-changes=false" >> $GITHUB_OUTPUT
            echo "ℹ️  No version changes detected"
            
            # Debug info
            echo "Current version: $current_version"
            echo "Previous version: $previous_version"
            
            # Check if package.json had other changes
            package_changed=$(git diff HEAD~1 HEAD --name-only | grep "apps/figma-plugin/package.json" || true)
            if [ -n "$package_changed" ]; then
              echo "📝 Note: package.json was modified but version remained the same"
              echo "    This could be dependency updates, script changes, etc."
            fi
          fi

      # Caches the Turborepo build artifacts stored in the `.turbo` directory.
      # This avoids re-running tasks on unchanged code, speeding up the build.
      # - name: Cache Turborepo
      #   uses: actions/cache@v4
      #   with:
      #     path: .turbo
      #     key: ${{ runner.os }}-turbo-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-turbo-

      # Runs the build step
      - name: Build
        run: npm run build
        env:
          VITE_RECURSICA_API_URL: ${{ secrets.RECURSICA_API }}
          VITE_RECURSICA_UI_URL: ${{ secrets.RECURSICA_API }}

      # This action has two modes:
      # 1. If changesets are present, it creates a "Version Packages" pull request.
      # 2. When the "Version Packages" PR is merged, it runs the `publish` command.
      # The `publish` command executes the `npm run release` script, which builds,
      # publishes to npm, and creates a GitHub Release.
      # NODE_AUTH_TOKEN is used by the `npm publish` command for authentication.
      - name: Create Release Pull Request or Publish to GitHub Releases
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Deploy to production when Version Packages PR is merged
      - name: Deploy Figma Plugin to Production
        if: steps.check-figma-plugin.outputs.has-figma-changes == 'true'
        uses: ./.github/actions/deploy-to-server
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          target_repository: ${{ github.repository_owner }}/recursica-server
          commit_sha: ${{ github.sha }}
          source_repo: ${{ github.repository }}
          environment: "prod"
          files_path: "apps/figma-plugin/dist/**/*"
          event_type: "trigger-server-deploy"
