name: Deploy PR Preview

# Builds and deploys Storybook previews for pull requests with "preview" in the title.
# Each PR gets a unique preview URL and automatic PR comments with the link.
#
# Usage: Include "preview" (case insensitive) in your PR title to trigger a preview build.
# Example titles: "Add button component - preview", "PREVIEW: Update theme"
#
# Prerequisites:
# - GitHub Pages enabled with "Deploy from a branch" (gh-pages branch)
# - recursica-storybook app with working "build-storybook" script
#
# Preview URLs: https://[username].github.io/recursica/pr-preview/pr-[pr-number]/

on:
  # Trigger on pull requests targeting main branch
  # Note: Preview builds only run if PR title contains "preview"
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches: [main]
  # Allow manual triggering from GitHub Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

# Allow concurrent deployments for different PRs
concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.title, 'preview') || contains(github.event.pull_request.title, 'Preview') || contains(github.event.pull_request.title, 'PREVIEW')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci
        env:
          HUSKY: 0

      - name: Build Storybook
        if: github.event.action != 'closed'
        run: npx turbo run build-storybook --filter=recursica-storybook

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./apps/recursica-storybook/storybook-static
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
